/* =========================================================================
   WORLDS PACK (data only). The party engine matches a group to these. Entry fields:
     scope      "universe" (a whole franchise or mythology) or "world" (one specific setting)
     needs      MATCHING LOGIC: facet -> weight on the group's average (negative = low is better)
     attrs      how the world feels, 1 to 5 each, in this order:
                difficulty, cooperation, danger, optimism, creativity, adaptability, leadership, exploration, survival
     blurb      description        why   the sentence about this group ({loves} + role tokens such as {leader}, {scout})
   The original 21 entries live in pack-party.js; this file adds the rest and a "universesMeta" overlay that gives
   those 21 their scope and attrs, so nothing already shipped was edited. Read merged entries with Forge.packs.merged("universes").
   ========================================================================= */
(function(F){
  "use strict";
  if (!F.packs) return;
  const A = F.packs.add;

  A("universesMeta", [
    { id: "marvel", scope: "universe", attrs: [3, 4, 3, 4, 4, 4, 4, 3, 3] },
    { id: "dc", scope: "universe", attrs: [3, 4, 3, 4, 3, 3, 5, 3, 3] },
    { id: "hogwarts", scope: "world", attrs: [2, 4, 3, 4, 4, 3, 3, 5, 2] },
    { id: "middle-earth", scope: "universe", attrs: [4, 5, 4, 3, 2, 3, 4, 5, 4] },
    { id: "star-wars", scope: "universe", attrs: [4, 4, 4, 4, 3, 4, 4, 5, 3] },
    { id: "westeros", scope: "world", attrs: [5, 2, 5, 1, 2, 4, 5, 3, 5] },
    { id: "resident-evil", scope: "world", attrs: [5, 4, 5, 2, 2, 4, 3, 3, 5] },
    { id: "mass-effect", scope: "universe", attrs: [4, 5, 4, 4, 3, 4, 5, 5, 3] },
    { id: "witcher", scope: "world", attrs: [4, 2, 4, 2, 2, 4, 2, 4, 4] },
    { id: "piltover", scope: "world", attrs: [4, 2, 3, 3, 5, 4, 3, 3, 3] },
    { id: "four-nations", scope: "world", attrs: [3, 5, 3, 5, 3, 4, 3, 5, 3] },
    { id: "grand-line", scope: "world", attrs: [4, 5, 4, 5, 3, 5, 4, 5, 4] },
    { id: "hidden-leaf", scope: "world", attrs: [4, 4, 4, 4, 3, 3, 4, 2, 4] },
    { id: "paradis", scope: "world", attrs: [5, 4, 5, 2, 2, 3, 5, 3, 5] },
    { id: "baker-street", scope: "world", attrs: [3, 3, 2, 3, 3, 3, 3, 4, 2] },
    { id: "olympus", scope: "universe", attrs: [4, 2, 4, 3, 3, 3, 5, 4, 3] },
    { id: "night-city", scope: "world", attrs: [5, 2, 5, 2, 4, 5, 2, 3, 5] },
    { id: "tavern", scope: "world", attrs: [2, 5, 3, 5, 4, 4, 3, 5, 3] },
    { id: "island", scope: "world", attrs: [4, 4, 4, 3, 3, 5, 3, 3, 5] },
    { id: "sitcom", scope: "world", attrs: [1, 4, 1, 4, 3, 3, 2, 1, 1] },
    { id: "starship", scope: "world", attrs: [3, 5, 3, 4, 4, 3, 4, 5, 3] },
  ]);

  const W = (id, name, franchise, scope, attrs, needs, blurb, why) => ({ id, name, franchise, scope, attrs, needs, blurb, why });
  A("universes", [
    W("pokemon", "The Pokémon World", "Pokémon", "universe", [2, 4, 2, 5, 3, 4, 3, 5, 2], { explore: 1, optimism: 0.9, persist: 0.8, warmth: 0.7, trust: 0.7, compete: 0.5 },
      "A world built on exploration and friendly rivalry, where partnership is the strongest power there is.",
      "It rewards {loves}, and your group has plenty of both. {scout} would already be halfway to the next town."),
    W("norse", "The Norse Worlds", "Norse mythology", "universe", [5, 3, 5, 2, 3, 3, 4, 4, 5], { persist: 1, boldness: 0.9, steadiness: 0.6, trust: 0.6, compete: 0.4, optimism: -0.4 },
      "A harsh, honorable cosmos where fate is real and courage is the only sensible answer.",
      "It rewards {loves}. {push} would keep everyone walking through the cold and {leader} would give the speech that makes it feel worth it."),
    W("egyptian", "Ancient Egypt of the Gods", "Egyptian mythology", "universe", [3, 3, 3, 3, 3, 2, 4, 3, 3], { structure: 0.9, patience: 0.8, steadiness: 0.7, analysis: 0.6, trust: 0.4, autonomy: -0.2 },
      "A world of ritual, judgment and order, where everyone has a role and the roles matter.",
      "It rewards {loves}. {strategist} would run the schedule and {carry} would keep every ritual from slipping."),
    W("arthurian", "Camelot and the Round Table", "Arthurian legend", "universe", [3, 5, 3, 4, 2, 2, 5, 3, 3], { trust: 0.9, initiative: 0.7, warmth: 0.7, structure: 0.6, persist: 0.6, optimism: 0.5 },
      "A kingdom held together by an ideal, and by people who keep choosing to believe in it.",
      "It rewards {loves}. {leader} would hold the table together and {sacrifice} would be the first to ride out."),
    W("hindu", "The Epic World of Dharma", "Hindu epics", "universe", [4, 4, 4, 3, 3, 3, 5, 4, 3], { persist: 0.8, structure: 0.7, trust: 0.7, steadiness: 0.7, analysis: 0.5, warmth: 0.5 },
      "A world of duty, devotion and hard moral questions, where every choice is a test of character.",
      "It rewards {loves}. {strategist} would weigh every consequence and {sacrifice} would act on the answer."),
    W("bleach", "Soul Society", "Bleach", "world", [4, 4, 4, 3, 2, 3, 4, 3, 4], { boldness: 0.9, persist: 0.9, compete: 0.7, trust: 0.6, structure: 0.5, warmth: 0.4 },
      "A world of captains, squads and fights that are really about who people choose to protect.",
      "It rewards {loves}. {push} would never stop training and {leader} would make a squad out of whoever shows up."),
    W("hxh", "The Hunter World", "Hunter x Hunter", "world", [5, 3, 5, 3, 4, 5, 3, 5, 5], { explore: 0.9, flex: 0.9, analysis: 0.7, boldness: 0.7, autonomy: 0.6, compete: 0.6, trust: -0.2 },
      "A vast, risky world where a license opens any door and the exams are the easy part.",
      "It rewards {loves}. {scout} would take the dangerous door and {solver} would find the trick in the test."),
    W("demon-slayer", "Taisho-Era Demon Hunting", "Demon Slayer", "world", [4, 5, 5, 3, 2, 3, 3, 2, 4], { persist: 1, warmth: 0.8, trust: 0.7, steadiness: 0.6, boldness: 0.6, structure: 0.5 },
      "A world where relentless training and real compassion matter more than raw talent.",
      "It rewards {loves}. {peace} would look after everyone's spirits and {push} would turn it into momentum."),
    W("jjk", "Jujutsu High and the Curse World", "Jujutsu Kaisen", "world", [5, 3, 5, 2, 3, 5, 3, 3, 5], { boldness: 0.8, flex: 0.8, humor: 0.5, autonomy: 0.6, compete: 0.6, analysis: 0.5, steadiness: 0.4 },
      "A modern world with something hungry hiding in it, where humor and nerve are survival skills.",
      "It rewards {loves}. {chaos} would make the plan up as it goes and {strategist} would quietly make it work."),
    W("chainsaw", "A Devil-Haunted Japan", "Chainsaw Man", "world", [5, 2, 5, 1, 3, 5, 2, 2, 5], { flex: 0.9, humor: 0.7, boldness: 0.8, autonomy: 0.6, structure: -0.7, trust: -0.3, steadiness: -0.3 },
      "A bleak, funny, chaotic world where people survive by improvising and holding onto small joys.",
      "It rewards {loves}. {chaos} would treat every disaster as a story and {heart} would keep you from losing the plot."),
    W("frieren", "The Age After the Hero", "Frieren", "world", [2, 4, 2, 4, 3, 3, 2, 5, 2], { patience: 1, explore: 0.9, warmth: 0.7, steadiness: 0.7, analysis: 0.5, persist: 0.5, social: -0.3 },
      "A quiet, wistful world that comes after the big adventure, where small moments are the real treasure.",
      "It rewards {loves}. {scout} would wander off to see what's next and {peace} would make sure the moment isn't missed."),
    W("vinland", "Viking-Age Vinland", "Vinland Saga", "world", [5, 3, 5, 2, 2, 3, 4, 4, 5], { persist: 0.9, steadiness: 0.7, boldness: 0.7, structure: 0.4, warmth: 0.4, optimism: -0.4 },
      "A harsh world of raids and farms, where the hardest battle is deciding what kind of person to be.",
      "It rewards {loves}. {carry} would build the farm and {sacrifice} would keep it from being burned."),
    W("fma", "Amestris", "Fullmetal Alchemist", "world", [4, 4, 4, 3, 5, 3, 4, 4, 3], { analysis: 0.9, persist: 0.9, invent: 0.8, warmth: 0.6, structure: 0.5, trust: 0.5, initiative: 0.5 },
      "A world where science and sacrifice go hand in hand, and every gain has a price.",
      "It rewards {loves}. {solver} would find the principle behind the problem and {sacrifice} would pay for it so no one else had to."),
    W("death-note", "The Game of Wits", "Death Note", "world", [4, 1, 3, 1, 3, 3, 3, 2, 2], { analysis: 1.2, structure: 0.7, compete: 0.8, autonomy: 0.6, steadiness: 0.7, trust: -0.9, warmth: -0.3 },
      "A world of quiet duels where every conversation is a move and trust is the first thing to go.",
      "It rewards {loves}. {strategist} would see three moves ahead and {skeptic} would be the only one to check twice."),
    W("god-of-war", "The Nine Realms", "God of War", "world", [5, 3, 5, 2, 2, 3, 3, 5, 5], { persist: 0.9, steadiness: 0.7, boldness: 0.7, warmth: 0.5, patience: 0.4, structure: 0.4, explore: 0.5 },
      "A mythic journey across brutal realms, where the real trial is learning to be a family.",
      "It rewards {loves}. {carry} would hold the line and {scout} would find the next way through."),
    W("metal-gear", "Cold War Espionage", "Metal Gear", "world", [5, 2, 5, 2, 3, 5, 3, 3, 5], { flex: 0.9, steadiness: 0.8, analysis: 0.7, autonomy: 0.7, persist: 0.7, trust: -0.5 },
      "A world of infiltration, improvisation and impossible loyalties, where nothing is what it looks like.",
      "It rewards {loves}. {scout} would slip past the guards and {skeptic} would question the briefing."),
    W("persona", "Palace Heists and Hidden Hearts", "Persona", "world", [3, 5, 4, 4, 4, 5, 4, 3, 2], { flex: 0.9, trust: 0.8, social: 0.7, analysis: 0.6, boldness: 0.6, initiative: 0.6, humor: 0.4 },
      "A stylish world of secret teams, double lives and friendships that turn out to be the real power.",
      "It rewards {loves}. {leader} would plan the heist and {heart} would keep everyone together after it."),
    W("red-dead", "The Wild West Frontier", "Red Dead Redemption", "world", [4, 3, 4, 2, 2, 4, 3, 5, 5], { persist: 0.8, autonomy: 0.8, boldness: 0.7, steadiness: 0.6, trust: 0.4, flex: 0.5, structure: -0.3 },
      "A fading frontier of loyalty, honor and hard choices, where a good horse and a good friend matter most.",
      "It rewards {loves}. {carry} would keep camp running and {scout} would find the next place to be."),
    W("half-life", "City 17 and the Resistance", "Half-Life", "world", [4, 4, 4, 3, 5, 5, 3, 4, 4], { flex: 0.9, invent: 0.8, analysis: 0.7, persist: 0.8, trust: 0.7, optimism: 0.5, boldness: 0.6 },
      "A world under occupation where cleverness and improvisation keep a resistance alive.",
      "It rewards {loves}. {solver} would hack whatever needs hacking and {leader} would turn a few people into a movement."),
    W("portal", "Aperture Science", "Portal", "world", [4, 1, 3, 2, 5, 4, 1, 3, 3], { analysis: 1, persist: 0.9, flex: 0.8, autonomy: 0.7, humor: 0.5, patience: 0.6, trust: -0.4 },
      "A cheerfully menacing testing facility where every problem has a clever answer and nobody tells you the rules.",
      "It rewards {loves}. {solver} would crack the chamber and {skeptic} would refuse the cake."),
    W("pirates", "The Golden Age of Piracy", "Pirates of the Caribbean", "world", [3, 3, 4, 4, 3, 5, 4, 5, 3], { flex: 0.9, boldness: 0.9, humor: 0.6, autonomy: 0.7, social: 0.6, structure: -0.7, compete: 0.4 },
      "A sunlit world of charm, treachery and very flexible plans, where improvisation beats strategy.",
      "It rewards {loves}. {chaos} would talk the crew into a plan and {strategist} would quietly make it real."),
    W("doctor-who", "All of Time and Space", "Doctor Who", "universe", [3, 4, 3, 5, 5, 5, 3, 5, 3], { explore: 1.1, flex: 0.9, optimism: 0.8, analysis: 0.8, humor: 0.6, warmth: 0.6, boldness: 0.7 },
      "A universe of curiosity, where every door opens onto another century and talking is often the best weapon.",
      "It rewards {loves}. {scout} would open the door and {heart} would make friends before anyone said hello."),
    W("house", "A Teaching Hospital", "House M.D.", "world", [3, 3, 2, 2, 3, 3, 3, 2, 1], { analysis: 1.1, persist: 0.8, compete: 0.6, structure: 0.5, patience: 0.3, autonomy: 0.5, warmth: -0.2 },
      "A world of puzzles with a pulse, where the diagnosis is everything and bedside manner is optional.",
      "It rewards {loves}. {solver} would crack the case and {skeptic} would be the one to say it's not what it looks like."),
    W("friends", "A Group of Friends in a Big City", "Friends", "world", [1, 5, 1, 4, 3, 3, 2, 2, 1], { social: 1, humor: 1, warmth: 0.9, trust: 0.8, optimism: 0.5, flex: 0.4 },
      "A warm world of apartments, coffee and the friends who feel like family.",
      "It rewards {loves}. {heart} would host everyone and {chaos} would turn dinner into an episode."),
    W("b99", "A Brooklyn Precinct", "Brooklyn Nine-Nine", "world", [2, 5, 2, 4, 3, 3, 4, 2, 2], { humor: 0.9, trust: 0.9, persist: 0.7, initiative: 0.6, warmth: 0.7, compete: 0.5, social: 0.7, structure: 0.3 },
      "A world of serious work and ridiculous people, where trust and a good bit are equal parts of the job.",
      "It rewards {loves}. {leader} would keep the squad in line and {chaos} would keep it from being boring."),
    W("office", "The Scranton Branch", "The Office", "world", [1, 4, 1, 3, 2, 3, 2, 1, 1], { social: 0.8, humor: 0.9, warmth: 0.7, structure: -0.3, flex: 0.4, trust: 0.3, compete: 0.3 },
      "A world of paperwork, personalities and surprisingly strong bonds.",
      "It rewards {loves}. {heart} would organize the party and {strategist} would quietly run the actual business."),
    W("regency", "Regency England", "Pride and Prejudice", "world", [2, 3, 1, 3, 2, 2, 2, 2, 1], { analysis: 0.5, structure: 0.7, social: 0.7, patience: 0.7, trust: 0.5, humor: 0.5, autonomy: 0.3, warmth: 0.4 },
      "A world of letters, balls and carefully chosen words, where wit is a social skill.",
      "It rewards {loves}. {detail} would notice every glance and {peace} would handle every dinner conversation."),
    W("gothic", "Gothic Europe", "Gothic fiction", "world", [4, 2, 4, 1, 3, 3, 2, 3, 3], { analysis: 0.8, steadiness: 0.7, autonomy: 0.7, persist: 0.6, explore: 0.5, optimism: -0.6, social: -0.4 },
      "A candle-lit world of old castles, strange experiments and long, uneasy nights.",
      "It rewards {loves}. {detail} would find the hidden room and {skeptic} would insist on leaving."),
    W("paris", "Nineteenth-Century Paris", "French literature", "world", [4, 3, 3, 3, 3, 3, 3, 2, 3], { persist: 0.9, warmth: 0.8, structure: 0.5, steadiness: 0.7, patience: 0.5, trust: 0.4, analysis: 0.4 },
      "A city of barricades, bakeries and second chances, where character is built the slow way.",
      "It rewards {loves}. {carry} would keep people fed and {sacrifice} would stand at the barricade."),
    W("gotham", "Gotham City", "DC Comics", "world", [5, 2, 5, 1, 3, 4, 3, 3, 5], { persist: 1, analysis: 0.9, autonomy: 0.8, structure: 0.7, optimism: -0.7, trust: -0.6, boldness: 0.5 },
      "A rain-soaked city that rewards preparation, nerve and a very good support team.",
      "It rewards {loves}. {strategist} would have a plan for everything and {carry} would keep it all running behind the scenes."),
    W("marvel-cosmic", "The Cosmic Marvel Galaxy", "Marvel Comics", "world", [3, 4, 4, 4, 4, 5, 3, 5, 3], { humor: 0.9, flex: 0.9, boldness: 0.8, social: 0.7, trust: 0.6, explore: 0.7, structure: -0.4 },
      "A bright, wild galaxy of misfit crews, strange planets and big feelings.",
      "It rewards {loves}. {chaos} would pick the weirdest planet and {heart} would make the crew feel like family."),
    W("wasteland", "A Wasteland", "Post-apocalypse", "world", [5, 3, 5, 1, 3, 5, 3, 4, 5], { persist: 1, flex: 0.9, steadiness: 0.7, boldness: 0.7, autonomy: 0.6, structure: 0.4, optimism: -0.5 },
      "A scorched world where fuel, water and trust are the only currencies.",
      "It rewards {loves}. {carry} would keep the engine alive and {leader} would pick where to drive."),
    W("noir-city", "A Noir Crime City", "Noir", "world", [4, 2, 4, 1, 3, 4, 3, 2, 4], { analysis: 0.9, autonomy: 0.8, flex: 0.7, trust: -0.8, compete: 0.6, persist: 0.6, optimism: -0.5 },
      "A neon-wet city of angles, favors and people who always want something.",
      "It rewards {loves}. {skeptic} would see the angle first and {detail} would find the loose thread."),
    W("panem", "Panem", "The Hunger Games", "world", [5, 3, 5, 2, 3, 5, 4, 3, 5], { persist: 1, flex: 0.9, steadiness: 0.7, warmth: 0.6, trust: 0.4, boldness: 0.7, optimism: -0.3 },
      "A harsh world where survival depends on resilience, resourcefulness and who you choose to protect.",
      "It rewards {loves}. {carry} would keep the group fed and {sacrifice} would step forward when it counted."),
    W("multiverse", "The Multiverse", "Science fiction", "universe", [4, 2, 4, 2, 5, 5, 2, 5, 3], { invent: 1, flex: 1, analysis: 0.8, humor: 0.8, explore: 0.8, structure: -0.8, steadiness: -0.3 },
      "Every reality at once, which is brilliant for inventors and exhausting for planners.",
      "It rewards {loves}. {solver} would build the gadget and {chaos} would press the button."),
    W("mystery-town", "Haunted Towns and Paranormal Mysteries", "Mystery fiction", "world", [2, 5, 3, 4, 4, 4, 3, 4, 2], { analysis: 0.8, explore: 0.8, humor: 0.7, trust: 0.7, warmth: 0.6, persist: 0.6, boldness: 0.5 },
      "A cozy kind of spooky: foggy streets, strange noises and a team that always works it out.",
      "It rewards {loves}. {detail} would find the clue and {heart} would keep everyone's courage up."),
    W("wonderland", "Wonderland", "Fantasy", "world", [3, 2, 3, 3, 5, 5, 1, 5, 2], { explore: 1, flex: 0.9, humor: 0.7, invent: 0.7, optimism: 0.5, structure: -0.8, analysis: -0.2 },
      "A world where the rules are made up and the questions are better than the answers.",
      "It rewards {loves}. {scout} would follow the strangest rabbit and {skeptic} would argue with the Queen."),
    W("fairy-tale", "A Storybook Realm", "Fairy tales", "world", [2, 4, 3, 5, 5, 3, 3, 4, 2], { optimism: 0.9, trust: 0.8, warmth: 0.8, persist: 0.6, boldness: 0.6, explore: 0.6, analysis: -0.3 },
      "A hopeful world of quests, talking animals and people who believe in doing the right thing.",
      "It rewards {loves}. {heart} would charm the dragon and {leader} would believe in the quest long enough to finish it."),
    W("american-south", "Maycomb, 1930s", "To Kill a Mockingbird", "world", [3, 3, 2, 3, 2, 2, 3, 1, 2], { steadiness: 0.9, warmth: 0.7, patience: 0.8, trust: 0.5, structure: 0.6, persist: 0.7, boldness: 0.3 },
      "A small town where conscience is tested slowly and quietly, one decision at a time.",
      "It rewards {loves}. {peace} would keep the neighbors talking and {sacrifice} would stand in the doorway."),
    W("frontier-space", "A Space Frontier", "Science fiction", "world", [4, 2, 4, 2, 3, 5, 2, 4, 4], { flex: 1, autonomy: 0.9, humor: 0.7, boldness: 0.6, structure: -0.7, trust: -0.2, explore: 0.6 },
      "A scruffy, jazzy frontier where crews scrape by on skill, luck and a good bounty.",
      "It rewards {loves}. {chaos} would find the job and {scout} would find the trouble."),
  ]);
})(typeof Forge !== "undefined" ? Forge : (globalThis.Forge = globalThis.Forge || {}));
if (typeof module !== "undefined" && module.exports) module.exports = Forge;
