/* =========================================================================
   ORGANIZATIONS, part two: Middle-earth, role-playing games, cyberpunk, Persona and anime. Same shape as pack-orgs.js. Original wording written for Forge.
   ========================================================================= */
(function(F){
  "use strict";
  if (!F.packs) return;
  const O = (id, name, franchise, group, needs, blurb, rewards, struggles, roles, culture, leadership, communication, conflict) => ({ id, name, franchise, group, needs, blurb, rewards, struggles, roles: { lead: roles[0], care: roles[1], brain: roles[2], wild: roles[3] }, culture, leadership, communication, conflict });

  F.packs.add("orgs", [
    /* ---- The Lord of the Rings ---- */
    O("the-fellowship", "The Fellowship", "The Lord of the Rings", "The Lord of the Rings", { persist: 1, trust: 0.9, steadiness: 0.7, warmth: 0.7, boldness: 0.5, patience: 0.5 }, "Nine very different travellers who agree to carry one impossible job together.", "Loyalty, endurance and humility.", "The proud, the possessive and the easily tempted.",
      ["Guide-captain", "Companion", "Lore-keeper", "Scout"], "Humble, loyal and weary, with long walks and shared pipe-weed.", "Whoever knows the road and is willing to listen.", "Honest, plain and often quiet.", "Settled around a fire, with honesty."),
    O("rangers-of-the-north", "The Rangers of the North", "The Lord of the Rings", "The Lord of the Rings", { steadiness: 0.9, autonomy: 0.7, patience: 0.8, explore: 0.7, persist: 0.8, social: -0.4 }, "A secretive brotherhood of wanderers who guard other people's peace without being thanked.", "Endurance, self-reliance and quiet duty.", "The showy, the sociable and anyone who needs recognition.",
      ["Chieftain", "Healer", "Tracker-scholar", "Wilderness scout"], "Quiet, weathered and loyal, with very few words and a very long memory.", "A chieftain by lineage and merit.", "Sparse, practical and observant.", "Handled privately and gently."),
    O("white-council", "The White Council", "The Lord of the Rings", "The Lord of the Rings", { analysis: 0.9, patience: 0.8, steadiness: 0.7, structure: 0.4, trust: 0.3, autonomy: 0.4 }, "A council of the wisest, who discuss great problems with great patience and sometimes too little action.", "Wisdom, restraint and foresight.", "The impulsive, the hasty and the impatient.",
      ["Head of council", "Counsellor", "Lore-master", "Wandering envoy"], "Deliberate, learned and cautious, with long meetings and short results.", "The eldest and most respected.", "Considered, formal and slow.", "Debated at length."),
    /* ---- Mass Effect ---- */
    O("normandy-crew", "The Normandy Crew", "Mass Effect", "Mass Effect", { trust: 0.9, initiative: 0.7, analysis: 0.6, warmth: 0.6, persist: 0.7, flex: 0.6 }, "A ship's company of soldiers, scientists and one very opinionated pilot, who function as a family.", "Competence, loyalty and a sense of humour.", "The unreliable, the secretive and the dogmatic.",
      ["Commander", "Crew counsellor", "Chief science officer", "Pilot"], "Warm, professional and slightly irreverent, with shore leave and inside jokes.", "A trusted captain who delegates.", "Clear in the field and chatty in the mess.", "Settled in the mess, usually with a joke."),
    O("n7", "The N7 Program", "Mass Effect", "Mass Effect", { persist: 0.9, steadiness: 0.8, boldness: 0.7, structure: 0.7, initiative: 0.6, humor: -0.1 }, "A rigorous special-forces training programme whose graduates are expected to do the impossible and file the paperwork.", "Discipline, resilience and adaptability.", "The soft, the scattered and the self-doubting.",
      ["Squad leader", "Combat medic", "Tactical analyst", "Assault specialist"], "Elite, demanding and proud, with strict standards.", "A senior officer who holds everyone to the highest bar.", "Concise, tactical and professional.", "Resolved through drill and debrief."),
    O("spectres", "The Spectres", "Mass Effect", "Mass Effect", { autonomy: 0.9, flex: 0.8, initiative: 0.8, analysis: 0.6, trust: -0.2, boldness: 0.6 }, "A handful of galactic agents who answer to the council and, in practice, to their own judgement.", "Judgement, independence and nerve.", "The rule-bound, the cautious and the easily intimidated.",
      ["Senior agent", "Contact", "Intelligence specialist", "Deep-cover operative"], "Solitary, trusted and slightly mysterious, with very short briefings.", "Each acts on their own authority.", "Terse, coded and discreet.", "Rarely conflict; mostly avoidance."),
    O("cerberus", "Cerberus", "Mass Effect", "Mass Effect", { compete: 0.8, analysis: 0.8, autonomy: 0.5, initiative: 0.8, trust: -0.5, optimism: -0.2 }, "A well-funded, ethically flexible human-first organisation that believes ends can justify most means.", "Pragmatism, ambition and a very flexible conscience.", "Idealists, rule-followers and the squeamish.",
      ["Director", "Handler", "Chief scientist", "Special operative"], "Corporate, secretive and driven, with a lot of sleek hardware.", "A charismatic, calculating figurehead.", "Compartmentalised and persuasive.", "Handled by quiet reassignment."),
    /* ---- Dragon Age ---- */
    O("grey-wardens", "The Grey Wardens", "Dragon Age", "Dragon Age", { persist: 0.9, steadiness: 0.8, boldness: 0.7, trust: 0.7, optimism: -0.3, autonomy: 0.3 }, "An order sworn to stand against the Blight, whatever it costs, and it will cost something.", "Sacrifice, duty and fortitude.", "The self-serving, the squeamish and the easily distracted.",
      ["Warden-Commander", "Quartermaster", "Lore-keeper", "Scout"], "Grim, loyal and a little fatalistic, with a strong camaraderie.", "A Warden-Commander chosen by merit.", "Plain-spoken and often grim.", "Settled by duty."),
    O("inquisition", "The Inquisition", "Dragon Age", "Dragon Age", { initiative: 0.8, trust: 0.8, flex: 0.7, analysis: 0.6, warmth: 0.5, persist: 0.7 }, "A new organisation with a large castle, a larger problem and a very diverse staff.", "Leadership, diplomacy and adaptability.", "The rigid, the secretive and the dismissive.",
      ["Inquisitor", "Spymaster's ally", "Advisor", "Field agent"], "Busy, diverse and slightly chaotic, with a lot of tables in the war room.", "A chosen figure who collects advisors.", "Open councils and a lot of letters.", "Argued in the war room."),
    O("templar-order", "The Templar Order", "Dragon Age", "Dragon Age", { structure: 0.9, steadiness: 0.8, persist: 0.7, trust: -0.2, autonomy: -0.4, compete: 0.3 }, "A military order sworn to guard against magic with discipline, devotion and a very large sword.", "Discipline, devotion and vigilance.", "The freewheeling, the creative and the independent.",
      ["Knight-Commander", "Chaplain", "Quartermaster", "Knight-Captain"], "Strict, devout and watchful, with a lot of drills.", "A formal hierarchy with a commander.", "Orders, rites and reports.", "Handled by regulation."),
    O("circle-of-magi", "The Circle of Magi", "Dragon Age", "Dragon Age", { analysis: 0.9, explore: 0.8, structure: 0.4, autonomy: 0.4, trust: 0.3, patience: 0.6 }, "A tower of scholars who live under supervision and make the best of the library.", "Scholarship, discretion and resilience.", "The anxious, the defiant and the anti-intellectual.",
      ["First Enchanter", "Healer", "Senior scholar", "Apprentice rebel"], "Studious, tense and clannish, with whispered rebellions in the stacks.", "A senior mage with a delicate balance of power.", "Cautious, coded and academic.", "Argued in committee and in corridors."),
    /* ---- Cyberpunk ---- */
    O("arasaka", "Arasaka", "Cyberpunk 2077", "Cyberpunk", { structure: 0.9, compete: 0.8, autonomy: -0.3, steadiness: 0.6, trust: -0.7, warmth: -0.5 }, "A towering megacorporation that treats loyalty as an asset and dissent as a defect.", "Obedience, ambition and polish.", "The rebellious, the sentimental and the independent.",
      ["Chairman", "Corporate liaison", "R&D director", "Security enforcer"], "Immaculate, formal and fearful, with a sense of ritual.", "A powerful, unchallenged head.", "Formal, vertical and guarded.", "Resolved by dismissal."),
    O("militech", "Militech", "Cyberpunk 2077", "Cyberpunk", { boldness: 0.8, compete: 0.8, flex: 0.6, initiative: 0.7, structure: 0.5, trust: -0.5 }, "An arms manufacturer that thinks of war as a growth sector and treats every conflict as a trade show.", "Competitiveness, nerve and salesmanship.", "The pacifist, the fussy and the squeamish.",
      ["CEO", "Customer liaison", "Weapons designer", "Field operator"], "Brash, aggressive and image-conscious, with a lot of branded armour.", "A forceful, profit-minded executive.", "Pitches, demos and threats.", "Settled by whoever has the better lawyers."),
    O("trauma-team", "Trauma Team International", "Cyberpunk 2077", "Cyberpunk", { steadiness: 0.9, structure: 0.7, warmth: 0.5, persist: 0.7, flex: 0.6, optimism: -0.2 }, "A premium emergency-response service that sells survival by subscription tier.", "Calm, speed and professionalism.", "The slow, the squeamish and those who need certainty.",
      ["Dispatch chief", "Paramedic", "Triage analyst", "Extraction pilot"], "Efficient, brisk and slightly commercial, with a corporate logo on everything.", "A pragmatic dispatcher.", "Fast, clear and clinical.", "Debriefed after the fact."),
    O("maxtac", "MaxTac", "Cyberpunk 2077", "Cyberpunk", { steadiness: 0.8, persist: 0.8, boldness: 0.7, structure: 0.6, trust: 0.4, optimism: -0.5 }, "A police unit that deploys when everything else has already gone wrong.", "Resilience, discipline and nerve.", "The nervous, the improvisers and the undecided.",
      ["Unit captain", "Medic", "Tactical analyst", "Heavy"], "Grim, tight-knit and weary, with black coffee and no small talk.", "A veteran captain who has seen all of it.", "Short, terse and coded.", "Dealt with in a terse, black-coffee debrief."),
    O("aldecaldos", "The Aldecaldos", "Cyberpunk 2077", "Cyberpunk", { trust: 0.9, warmth: 0.7, persist: 0.8, flex: 0.7, autonomy: 0.5, structure: 0.3 }, "A nomad clan that treats family, vehicles and honesty as everything.", "Loyalty, resourcefulness and plain speaking.", "The scheming, the individualistic and the squeamish.",
      ["Clan leader", "Camp elder", "Mechanic-engineer", "Scout driver"], "Warm, rough and communal, with a campfire and a lot of repairs.", "A respected elder who earns the role.", "Plain and direct.", "Settled around the fire."),
    /* ---- The Witcher ---- */
    O("wolf-school", "The School of the Wolf", "The Witcher", "The Witcher", { persist: 0.9, steadiness: 0.8, autonomy: 0.6, analysis: 0.5, trust: 0.4, optimism: -0.6 }, "A tiny, battered order of monster-hunters who train hard and trust few.", "Resilience, skill and a dry sense of humour.", "The sentimental, the soft-spoken and the credulous.",
      ["Master", "Camp keeper", "Alchemist", "Road warrior"], "Rough, loyal and wry, with a lot of road dust and unspoken affection.", "The oldest and most experienced.", "Short, dry and mostly implied.", "Settled by sparring."),
    O("lodge-of-sorceresses-org", "The Lodge of Sorceresses", "The Witcher", "The Witcher", { analysis: 0.9, initiative: 0.7, autonomy: 0.6, compete: 0.5, structure: 0.5, trust: -0.4 }, "A secretive sisterhood of powerful sorceresses with strong opinions about how kings should behave.", "Intelligence, ambition and subtlety.", "The naive, the impulsive and the sentimental.",
      ["Head of the Lodge", "Healer", "Researcher", "Diplomat-spy"], "Elegant, political and watchful, with a lot of private rivalries.", "A strong-willed senior sorceress.", "Elegant, coded and calculating.", "Handled through influence."),
    /* ---- Persona ---- */
    O("phantom-thieves-org", "The Phantom Thieves of Hearts", "Persona", "Persona", { boldness: 0.9, trust: 0.9, flex: 0.8, analysis: 0.6, humor: 0.5, structure: -0.1 }, "A band of students who steal corrupt desires and leave a calling card.", "Nerve, loyalty and improvisation.", "The reluctant, the secretive and the stingy with trust.",
      ["Leader", "Support", "Navigator", "Infiltrator"], "Stylish, loyal and slightly theatrical, with a shared hideout and lots of planning.", "A quiet, trusted leader.", "Group chats, plans and in-jokes.", "Argued over, then resolved by trust."),
    O("sees", "S.E.E.S.", "Persona", "Persona", { persist: 0.8, trust: 0.7, steadiness: 0.6, warmth: 0.6, structure: 0.5, humor: 0.4 }, "A dorm-based special extracurricular squad with a late-night schedule and a surprising amount of homework.", "Perseverance, teamwork and nerve.", "The solitary, the inconsistent and the cynical.",
      ["Leader", "Dorm support", "Researcher", "Frontline fighter"], "Youthful, loyal and tired, with a common room and instant noodles.", "A calm, chosen leader.", "Dorm chats and radio calls.", "Settled over late-night snacks."),
    O("investigation-team-org", "The Investigation Team", "Persona", "Persona", { trust: 0.9, analysis: 0.7, persist: 0.7, warmth: 0.7, flex: 0.5, humor: 0.5 }, "A group of friends in a small town who solve a case by sharing what they know and what they fear.", "Honesty, curiosity and loyalty.", "The secretive, the proud and the incurious.",
      ["Team leader", "Support", "Detective", "Frontliner"], "Warm, curious and a little awkward, with a food court and a shared notebook.", "A calm, trusted leader.", "Open and chatty.", "Talked through over snacks until it makes sense."),
    /* ---- Anime ---- */
    O("survey-corps", "The Survey Corps", "Attack on Titan", "Anime", { boldness: 0.9, persist: 0.9, trust: 0.8, steadiness: 0.7, structure: 0.5, optimism: -0.5 }, "The branch of the military that goes beyond the walls and mostly does not return.", "Courage, loyalty and acceptance of risk.", "The timid, the self-serving and those who need safety.",
      ["Commander", "Field medic", "Scholar-scientist", "Elite scout"], "Brave, brotherly and haunted, with a lot of funerals.", "A visionary commander who accepts the cost.", "Direct, clear and emotional.", "Settled in the mess hall."),
    O("gotei-13-org", "The Gotei 13", "Bleach", "Anime", { structure: 0.8, persist: 0.8, steadiness: 0.7, compete: 0.5, initiative: 0.6, trust: 0.4 }, "The thirteen divisions that keep the dead where they belong, each with a captain and a strong opinion.", "Strength, discipline and loyalty to one's division.", "The disloyal, the disorganised and the shy.",
      ["Captain-Commander", "Division healer", "Strategist", "Battle-lover"], "Proud, divisional and formal, with very distinct personalities.", "A Captain-Commander with long authority.", "Formal, with a lot of rank.", "Settled by duel or decree."),
    O("akatsuki-org", "The Akatsuki", "Naruto", "Anime", { autonomy: 0.8, compete: 0.7, analysis: 0.6, boldness: 0.7, trust: -0.7, optimism: -0.6 }, "A cabal of rogue powerhouses with a grand plan and very little affection for each other.", "Ambition, independence and conviction.", "The cooperative, the hopeful and the conventional.",
      ["Leader", "Handler", "Planner", "Wild partner"], "Cold, theatrical and mutually suspicious, with matching cloaks.", "A distant, ideological leader.", "Terse, coded and mostly via projection.", "Handled by threat."),
    O("straw-hat-pirates", "The Straw Hat Pirates", "One Piece", "Anime", { optimism: 1, boldness: 0.9, trust: 0.9, social: 0.7, flex: 0.7, structure: -0.6 }, "A crew of dreamers, each with a goal, who follow a captain with no plan but enormous heart.", "Loyalty, ambition and a ridiculous amount of optimism.", "The pessimistic, the secretive and the schedule-minded.",
      ["Captain", "Cook-healer", "Navigator", "Wild fighter"], "Loud, warm and chaotic, with a feast at every opportunity.", "A captain who is mostly a symbol.", "Shouted, hungry and honest.", "Settled by fists and food."),
    O("phantom-troupe-org", "The Phantom Troupe", "Hunter x Hunter", "Anime", { autonomy: 0.8, compete: 0.6, boldness: 0.8, trust: 0.4, warmth: -0.3, structure: 0.3 }, "A band of thieves who are loyal to one another and to nobody else.", "Skill, ruthlessness and loyalty to the group.", "The sentimental, the law-abiding and the disloyal.",
      ["Leader", "Informant", "Planner", "Fighter"], "Cold, tight-knit and cruel, with a strange code.", "A charismatic leader who is also replaceable.", "Brief and coded.", "Settled by vote or duel."),
    O("demon-slayer-corps-org", "The Demon Slayer Corps", "Demon Slayer", "Anime", { persist: 1, trust: 0.7, steadiness: 0.7, warmth: 0.6, structure: 0.6, humor: 0.2 }, "A secret organisation of swordsmen who have devoted their lives to protecting strangers from monsters.", "Perseverance, compassion and discipline.", "The cowardly, the selfish and the apathetic.",
      ["Patriarch", "Healer", "Strategist", "Pillar"], "Dedicated, grieving and supportive, with a lot of training.", "A gentle head and a council of strong Pillars.", "Respectful, formal and sincere.", "Settled by discipline."),
    O("public-safety-devil-hunters", "Public Safety Devil Hunters", "Chainsaw Man", "Anime", { boldness: 0.8, flex: 0.7, persist: 0.7, structure: 0.3, trust: 0.2, optimism: -0.5 }, "A government unit that hunts devils with contracts, rules and a high rate of staff turnover.", "Nerve, resilience and pragmatism.", "The cautious, the honest and those who value a long life.",
      ["Section chief", "Veteran", "Analyst", "Devil-contracted hunter"], "Cynical, tired and rough around the edges, with strict rules and darker jokes.", "A calm, commanding supervisor.", "Short and blunt.", "Handled by transfer."),
    O("night-raid", "Night Raid", "Akame ga Kill!", "Anime", { boldness: 0.8, trust: 0.9, persist: 0.8, autonomy: 0.4, steadiness: 0.6, optimism: -0.3 }, "A secret assassin cell that fights an unjust government and hopes nobody notices the cost.", "Loyalty, resolve and skill.", "The hesitant, the talkative and the weak-willed.",
      ["Boss", "Support medic", "Strategist", "Assassin"], "Close, tragic and fiercely loyal, with a hideout and a strong rhythm.", "A calm boss who cares for her people.", "Brief, honest and loving.", "Settled together."),
    O("hidden-leaf-village", "The Hidden Leaf Village", "Naruto", "Anime", { persist: 0.9, trust: 0.8, warmth: 0.7, structure: 0.5, optimism: 0.6, compete: 0.3 }, "A village of ninja where hard work, teamwork and a stubborn kind of hope are the main exports.", "Effort, loyalty and teamwork.", "The solitary, the cynical and those who value only talent.",
      ["Hokage", "Medic-ninja", "Strategist", "Special operative"], "Industrious, communal and proud, with a ramen shop on every corner.", "A respected elder who carries the village.", "Warm, direct and a little noisy.", "Settled by training together."),
    O("hunter-association", "The Hunter Association", "Hunter x Hunter", "Anime", { explore: 0.9, autonomy: 0.7, flex: 0.7, boldness: 0.7, analysis: 0.6, trust: 0.2 }, "A licensing body that gives adventurers the right to go anywhere and the rest is up to them.", "Curiosity, independence and nerve.", "The conventional, the cautious and those who need supervision.",
      ["Chairman", "Examiner", "Researcher", "Free-roaming hunter"], "Eccentric, adventurous and independent, with great regional food.", "A playful chairman with secret depths.", "Short, odd and playful.", "Settled by exam."),
    O("jujutsu-high", "Jujutsu High", "Jujutsu Kaisen", "Anime", { persist: 0.8, flex: 0.7, humor: 0.5, trust: 0.7, boldness: 0.6, optimism: -0.2 }, "A school for sorcerers who deal with the curses people leave behind, preferably before graduation.", "Resilience, adaptability and a sense of humour.", "The squeamish, the proud and the unprepared.",
      ["Principal", "Counsellor", "Researcher", "Frontline sorcerer"], "Casual, grim and affectionate, with dark jokes and strict hierarchy.", "A very strong, very flippant teacher.", "Light on the surface and serious below.", "Settled in a training match."),
    O("fairy-tail-guild-org", "The Fairy Tail Guild", "Fairy Tail", "Anime", { warmth: 0.9, trust: 0.9, boldness: 0.8, optimism: 0.8, humor: 0.7, structure: -0.5 }, "A guild that is also a family, a pub and a very good place to start a brawl.", "Loyalty, heart and a willingness to get involved.", "The cold, the secretive and those who dislike noise.",
      ["Guild Master", "Barkeep", "Archive mage", "Brawler"], "Warm, noisy and loving, with an open door and a broken table.", "A fatherly master who loves the chaos.", "Loud, honest and affectionate.", "Settled by a brawl and a feast."),
    O("black-bulls-org", "The Black Bulls", "Black Clover", "Anime", { boldness: 0.8, persist: 0.9, optimism: 0.8, humor: 0.6, trust: 0.6, structure: -0.6 }, "A squad of misfits who are treated as the weakest, and refuse to accept it.", "Determination, optimism and heart.", "The proud, the cynical and the rule-bound.",
      ["Captain", "Cook-supporter", "Mage-strategist", "Reckless fighter"], "Rowdy, cheerful and scrappy, with a rundown hideout and a lot of food.", "A gruff captain who trusts his squad.", "Loud and hearty.", "Settled by shouting and sparring."),
    O("nerv", "NERV", "Neon Genesis Evangelion", "Anime", { structure: 0.8, analysis: 0.8, steadiness: 0.6, trust: -0.3, optimism: -0.6, autonomy: 0.3 }, "A secret agency that protects humanity with machines, secrecy and a very anxious command centre.", "Competence, discretion and endurance.", "The emotionally fragile, the disobedient and the naive.",
      ["Commander", "Operations director", "Chief scientist", "Pilot"], "Tense, secretive and clinical, with long corridors and a lot of unspoken pain.", "A remote, authoritative commander.", "Clipped, technical and guarded.", "Settled by instructions."),
    O("wise-agency", "WISE", "Spy x Family", "Anime", { flex: 0.9, structure: 0.8, analysis: 0.8, steadiness: 0.7, autonomy: 0.4, trust: -0.3 }, "A discreet spy agency that sends skilled agents into impossible cover stories.", "Adaptability, discretion and precision.", "The chatty, the sentimental and the unprepared.",
      ["Handler", "Case-officer", "Intelligence analyst", "Field agent"], "Cool, careful and a little dry, with coded notes and perfect cover.", "A quiet handler who values results.", "Coded, concise and precise.", "Handled by recall."),
    O("military-state-alchemists", "The State Alchemists", "Fullmetal Alchemist", "Anime", { analysis: 0.9, structure: 0.7, initiative: 0.6, compete: 0.5, trust: -0.2, persist: 0.6 }, "A military corps of scientists who are paid to solve problems, and not paid to ask what the problems are for.", "Brilliance, discretion and obedience.", "The idealist, the secretive and the rebel.",
      ["Colonel", "Medical alchemist", "Research officer", "Field specialist"], "Formal, bureaucratic and ambitious, with a lot of stripes and a lot of secrets.", "A strategic officer with a hidden goal.", "Formal and polite.", "Settled by rank.")
  ]);
})(Forge);
