/* =========================================================================
   LENS + SCENARIO PACK (data only). Three lenses on the SAME compatibility result:
   the existing engine scores the pair; these entries only choose how it is told.

   section types (see experience.js):
     category  a compatibility category the engine already computed -> high/mid/low text + a 5-step meter
     who       which of the two leans furthest into a weighted set of facets
     duo       best-fitting two-role pairing (roles = facet weights for person 1 and person 2)
     pick      best single option for the pair's blended facets
     list      shared strengths / friction areas / activities already produced by the engine
   scenario: needs = facet weights the PAIR must cover (the stronger of the two counts most),
             lead = facet weights deciding who takes point; great/good/rough = authored outcomes.
   Tokens: {A} {B} {lead} {other} {first} {second}. Keep every line friendly and free of numbers.
   ========================================================================= */
(function(F){
  "use strict";
  if (!F.packs) return;
  const HL = (e, x, g, m, d, i) => ({ Exceptional: e, Excellent: x, Good: g, Mixed: m, Difficult: d, "Extremely Incompatible": i });

  F.packs.add("lenses", [
    /* ------------------------------------------------------------ FRIENDSHIP */
    { id: "friendship", name: "Friendship", icon: "🤝", eyebrow: "FRIENDSHIP", tone: "fun",
      blurb: "How well would these personalities work as friends?",
      headlines: HL(
        "{A} and {B} are the kind of duo other people tell stories about.",
        "{A} and {B} make a genuinely great team for any plan that involves leaving the house.",
        "{A} and {B} have a solid friendship with a few fun quirks to manage.",
        "{A} and {B} are an unlikely pair, which is exactly how the best adventures start.",
        "{A} and {B} would have an interesting time together. Not always easy, never dull.",
        "{A} and {B} would live the same adventure in completely different ways, which is a story in itself."),
      sections: [
        { id: "adventure", type: "category", category: "Adventure", title: "Adventure Compatibility", icon: "🧭",
          words: ["Needs a map", "Up for it", "Born explorers"],
          high: "{A} and {B} both lean into the unknown. Say 'let's just see where this goes' and you'll both mean it.",
          mid: "You're game for an adventure, just not always the same one. A little planning on one side, a little spontaneity on the other.",
          low: "One of you wants a plan and the other wants a surprise. Choose your adventures carefully and they go well." },
        { id: "problem", type: "category", category: "Problem Solving", title: "Problem Solving Together", icon: "🧩",
          words: ["Different angles", "Solid", "Unstoppable"],
          high: "Put you two in front of a puzzle and the puzzle loses. You see it from different sides and land on the same answer.",
          mid: "You'll get there. One of you wants to think it through and the other wants to try something, and that's often how it gets solved.",
          low: "Your approaches are very different, so expect a debate before a solution. Sometimes that's the point." },
        { id: "chaos", type: "who", title: "Who Starts The Chaos?", icon: "🎲", weights: { boldness: 1.5, humor: 1, flex: 1, structure: -1, patience: -0.5 },
          text: "{lead} is the one most likely to say 'what's the worst that could happen?' and mean it. {other} is the one who has to answer.",
          tie: "Neither of you has to start the chaos. It sort of starts itself once you're together." },
        { id: "alive", type: "who", title: "Who Keeps Everyone Alive?", icon: "🛟", weights: { steadiness: 1.5, structure: 1, warmth: 1, patience: 1, flex: 0.5 },
          text: "{lead} is the one counting supplies and noticing the exits. {other} keeps the mood up while they do it.",
          tie: "You're about equally good at keeping things from going sideways, which is a very good sign." },
        { id: "activities", type: "list", source: "activities", title: "Best Shared Activities", icon: "🎟️", intro: "Based on how you're both wired, these would probably go well:", empty: "Pick something neither of you has done before and find out." },
        { id: "strengths", type: "list", source: "shared", title: "Friendship Strengths", icon: "💪", intro: "What you've both got going for you:", empty: "You get along by being different. You'll discover your strengths as you go." },
        { id: "arguments", type: "list", source: "conflicts", title: "Potential Arguments", icon: "😤", intro: "Where you might bicker (lovingly):", empty: "Honestly, not much. You'd have to invent something to argue about." },
        { id: "trust", type: "category", category: "Trust", title: "Trust Between Friends", icon: "🔑", words: ["Earned slowly", "Solid", "Ride or die"],
          high: "You'd trust each other with the spare key, the secret and the last slice of pizza. It's the quiet kind of trust that doesn't need to be said.",
          mid: "Trust is there and still growing. A few honest moments and some kept promises will take it a long way.",
          low: "You may need time to feel sure of each other. Showing up when you said you would does more than any speech." },
        { id: "keepintouch", type: "category", category: "Communication", title: "Staying in Touch", icon: "💬", words: ["Hit and miss", "Easy enough", "Never out of sync"],
          high: "Messages, voice notes and long chats all come easily. You can go a week without talking and pick up mid-sentence.",
          mid: "You communicate well, with the odd gap. A quick 'thinking of you' keeps things warm between bigger catch-ups.",
          low: "You each keep in touch in a different way. Agree on what 'staying close' looks like and you'll be fine." },
        { id: "travel", type: "category", category: "Travel Partner", title: "Travelling Together", icon: "✈️", words: ["Pack patience", "Good travel buddies", "Dream travel team"],
          high: "You'd be the pair who finds the best street food, misses one train gracefully and comes home with a shared playlist.",
          mid: "A trip would work, with a bit of negotiating between the museum and the beach.",
          low: "You travel in different ways. Splitting a few days to do your own thing might be the secret to a great trip." },
        { id: "gaming", type: "category", category: "Gaming Partner", title: "Gaming Together", icon: "🎮", words: ["Rival energy", "Solid co-op", "Perfect co-op"],
          high: "Co-op with you two is a joy. You cover each other, share a very silly callout language and rarely blame the other.",
          mid: "You'd have fun, with the occasional 'you were supposed to be watching the left.'",
          low: "You play in very different ways. Pick a game where your styles help each other, or one where you're allowed to compete." },
        { id: "school", type: "category", category: "Study Partner", title: "School and Study Buddies", icon: "📚", words: ["Distracting", "Productive", "Dream study pair"],
          high: "You'd keep each other focused and still laugh. Revision sessions with you two end with an actual plan.",
          mid: "You'd get work done. A few off-topic detours are part of the deal.",
          low: "You study in different ways. A shared goal and separate methods could work better than sitting side by side." },
        { id: "projects", type: "category", category: "Creative Partner", title: "Projects and Hobbies", icon: "🎨", words: ["Different visions", "Good makers", "Creative sparks"],
          high: "Give you a blank page and an afternoon and something unexpected appears. Your ideas feed each other.",
          mid: "You'd make something good, once you agree on whose vision leads.",
          low: "You each have strong creative instincts. Take turns choosing the direction and you'll both be proud of the result." },
        { id: "workfriends", type: "category", category: "Teamwork", title: "Work Friendships", icon: "💼", words: ["Keep it casual", "Good colleagues", "Dream work buddies"],
          high: "You'd be the pair others want on their team: reliable, easy to read and fun at the coffee machine.",
          mid: "You'd work well together, and the lunch breaks would be the highlight.",
          low: "You work differently, so clear roles help. Your friendship will do fine outside the office." },
        { id: "duo", type: "duo", title: "What Kind Of Duo Are You?", icon: "🎭", duos: [
          { name: "The Chaos and the Plan", icon: "🎲", roles: [{ boldness: 1, flex: 0.5, humor: 0.5 }, { structure: 1, analysis: 0.5, steadiness: 0.5 }], text: "{first} lights the fuse and {second} makes sure there's a fire extinguisher nearby. It works more often than it should." },
          { name: "The Explorer and the Anchor", icon: "🧭", roles: [{ explore: 1, flex: 0.5, boldness: 0.5 }, { steadiness: 1, persist: 0.5, patience: 0.5 }], text: "{first} wanders off to find what's out there. {second} makes sure there's a way back." },
          { name: "The Hype Duo", icon: "📣", roles: [{ social: 1, humor: 1, optimism: 1 }, { social: 1, humor: 1, optimism: 1 }], text: "Two energy sources in one room. You make every plan sound like a great idea, and you're usually right." },
          { name: "The Strategist and the Wildcard", icon: "♟️", roles: [{ analysis: 1, structure: 0.5 }, { boldness: 1, flex: 1 }], text: "{first} reads the situation and {second} improvises past its weak spots. Opponents hate this." },
          { name: "The Quiet Pair", icon: "🌙", roles: [{ social: -1, analysis: 0.5, autonomy: 0.5 }, { social: -1, analysis: 0.5, autonomy: 0.5 }], text: "Few words, deep understanding. You can share a room for an hour and call it a great night." },
          { name: "The Heart and the Head", icon: "💡", roles: [{ warmth: 1, optimism: 0.5 }, { analysis: 1, structure: 0.5 }], text: "{first} remembers how everyone feels and {second} remembers how everything works. Together, you remember everything." },
          { name: "The Friendly Rivals", icon: "🥊", roles: [{ compete: 1, boldness: 0.5 }, { compete: 1, boldness: 0.5 }], text: "You'd turn a casual game into a season. You push each other to be better and neither of you would admit it was friendship." },
          { name: "The Makers", icon: "🛠️", roles: [{ invent: 1, explore: 0.5 }, { invent: 1, persist: 0.5 }], text: "Give you a free weekend and a pile of parts and something strange and wonderful appears." },
          { name: "The Steady Pair", icon: "⚓", roles: [{ steadiness: 1, patience: 1 }, { steadiness: 1, patience: 1 }], text: "Calm and reliable. Nothing is on fire, and if it was, one of you would already have the hose." },
          { name: "The Instigator and the Peacemaker", icon: "🕊️", roles: [{ boldness: 1, initiative: 1, compete: 0.5 }, { warmth: 1, patience: 1 }], text: "{first} starts things and {second} makes sure everyone is still speaking afterwards." },
        ] },
      ] },

    /* ------------------------------------------------------------ ROMANCE */
    { id: "romance", name: "Romance", icon: "❤️", eyebrow: "ROMANCE", tone: "warm",
      blurb: "What kind of relationship could these personalities build together?",
      headlines: HL(
        "{A} and {B} have the kind of foundation people hope for: easy to be together, and even better at facing things together.",
        "{A} and {B} have a lot going for them, and the differences are mostly the good kind.",
        "{A} and {B} have real warmth between them and a few things worth talking through.",
        "{A} and {B} come from different places, and that can build something strong if you stay curious about each other.",
        "{A} and {B} would need patience and honesty, which are worth a lot.",
        "{A} and {B} experience closeness and life in very different ways. Understanding each other would be the whole adventure."),
      sections: [
        { id: "comm", type: "category", category: "Communication", title: "Communication", icon: "💬", words: ["Learning each other", "Comfortable", "Easy"],
          high: "Talking comes easily to you two. You tend to say what you mean in a way the other one actually hears.",
          mid: "You communicate well enough and sometimes beautifully. A little extra care on the harder topics goes a long way.",
          low: "You each have your own language for feelings. Learning each other's takes time and is worth it." },
        { id: "support", type: "category", category: "Emotional Support", title: "Emotional Support", icon: "🫶", words: ["Growing", "Reliable", "Deeply caring"],
          high: "You notice when the other one is struggling and show up without being asked. That's rare, and it matters.",
          mid: "You support each other, though sometimes in different ways. Asking 'what do you need right now?' fills any gap.",
          low: "One of you might want to talk it through while the other wants space. Saying so out loud makes a big difference." },
        { id: "conflict", type: "category", category: "Conflict Resolution", title: "Conflict Resolution", icon: "🌦️", words: ["Needs practice", "Workable", "Graceful"],
          high: "Disagreements don't scare you. You can be honest, stay kind and get back to normal quickly.",
          mid: "You'll hit a rough patch now and then and get through it. Agreeing on how you fight helps.",
          low: "You handle tension very differently. The good news is that naming it early helps both of you feel safe." },
        { id: "trust", type: "category", category: "Trust", title: "Trust", icon: "🔑", words: ["Earned slowly", "Steady", "Rock solid"],
          high: "Trust seems to arrive easily between you, and it's the kind that gets stronger with time.",
          mid: "Trust builds steadily. Small, reliable moments will do more than any big gesture.",
          low: "Trust may take longer to build, and that's okay. Consistency matters more than intensity here." },
        { id: "longterm", type: "category", category: "Marriage", title: "Long-Term Compatibility", icon: "🌅", words: ["Open question", "Promising", "Built to last"],
          high: "Your day-to-day habits and long-haul values line up in a way that suggests you could grow old comfortably together.",
          mid: "You have a good base for the long run. A few conversations about what each of you wants will make it stronger.",
          low: "Over the long run you'd need to build a shared rhythm on purpose. It's possible, and it'd be yours." },
        { id: "living", type: "category", category: "Roommate", title: "Living Together", icon: "🏠", words: ["Needs negotiating", "Comfortable", "Effortless"],
          high: "Sharing a home would feel natural. You'd likely agree on the little things that usually cause the big arguments.",
          mid: "A shared home would work, with a few friendly negotiations about space, tidiness and noise.",
          low: "You'd each have strong opinions about how a home should feel. Agree on the basics early and enjoy the rest." },
        { id: "future", type: "category", category: "Life Goals", title: "Shared Future", icon: "🗺️", words: ["Different paths", "Pointing the same way", "Same horizon"],
          high: "You seem to want similar things from life, which makes planning together feel like teamwork.",
          mid: "Your goals overlap in the places that matter. Talk about the rest and you'll find ways to make room.",
          low: "You may be heading toward different horizons. The most important thing is to talk about it honestly and early." },
        { id: "needs", type: "category", category: "Emotional Intelligence", title: "Emotional Needs", icon: "💗", words: ["Still learning", "Attuned", "Very in tune"],
          high: "You tend to sense what the other needs before it's said, and you're comfortable giving it.",
          mid: "You're often in tune and sometimes miss each other. Asking beats guessing, every time.",
          low: "You each need different things to feel cared for. Learning each other's list is a lovely project." },
        { id: "affection", type: "pick", title: "How You Show Affection", icon: "💞", options: [
          { name: "Playful teasing", icon: "😄", needs: { humor: 1, social: 0.6, flex: 0.4 }, text: "Affection arrives as jokes, nicknames and shared nonsense. It's how you say 'I like being around you.'" },
          { name: "Quiet steadiness", icon: "🕯️", needs: { steadiness: 1, patience: 0.8, social: -0.4 }, text: "You show it by being there. Small, dependable gestures matter more to you than big declarations." },
          { name: "Open warmth", icon: "☀️", needs: { warmth: 1.2, trust: 0.8, optimism: 0.5 }, text: "You say it, show it and mean it. Nobody in this relationship wonders where they stand." },
          { name: "Doing things for each other", icon: "🛠️", needs: { structure: 0.8, persist: 0.8, warmth: 0.6 }, text: "Love looks like a cooked meal, a fixed bike and a plan that includes the other person." },
          { name: "Adventures shared", icon: "🌄", needs: { explore: 1, boldness: 0.7, flex: 0.6 }, text: "You bond over new places and shared firsts. The memories you make are the way you say it." },
        ] },
        { id: "love", type: "pick", title: "Love Languages", icon: "💌", options: [
          { name: "Words that mean something", icon: "✍️", needs: { social: 0.8, warmth: 0.8, analysis: 0.3, humor: 0.3 }, text: "A well-chosen sentence, a note or a voice message lands deeply with you two." },
          { name: "Time together", icon: "⏳", needs: { warmth: 1, patience: 0.8, social: -0.2 }, text: "Undivided attention is your currency. A quiet evening together means more than anything wrapped." },
          { name: "Acts of care", icon: "🧺", needs: { structure: 0.9, persist: 0.7, warmth: 0.6 }, text: "You feel loved when someone makes your life a little easier without being asked." },
          { name: "Surprises and thoughtful gifts", icon: "🎁", needs: { invent: 0.9, explore: 0.5, warmth: 0.6, humor: 0.4 }, text: "The best moments are the little unexpected ones, chosen because they're exactly you." },
          { name: "Shared experiences", icon: "🎟️", needs: { explore: 0.9, boldness: 0.6, social: 0.6, flex: 0.5 }, text: "Doing something together, whether trying a class or chasing a sunrise, is how love sinks in." },
        ] },
        { id: "parenting", type: "pick", title: "Parenting Style, If It Ever Comes Up", icon: "🍼", options: [
          { name: "The playful household", icon: "🪁", needs: { humor: 1, optimism: 0.7, flex: 0.6, structure: -0.4 }, text: "Fun first. Home would be loud, creative and full of made-up games, with just enough structure to keep it running." },
          { name: "The steady home", icon: "🏡", needs: { steadiness: 1, structure: 0.8, patience: 0.8 }, text: "Predictable, calm and safe. Routines would be gentle, and kids would always know where they stand." },
          { name: "The curious household", icon: "🔭", needs: { explore: 1, analysis: 0.6, flex: 0.6, optimism: 0.4 }, text: "Questions are welcome at the table. Museums, books and 'let's find out' would be family habits." },
          { name: "The warm, close family", icon: "🧸", needs: { warmth: 1.1, trust: 0.8, patience: 0.6 }, text: "Affection and listening would come first. Everyone would feel known and heard." },
          { name: "The independent family", icon: "🌱", needs: { autonomy: 1, trust: 0.6, flex: 0.6, structure: -0.2 }, text: "You'd encourage independence early and trust your kids to find their own way, with a safety net nearby." },
        ] },
        { id: "attract", type: "duo", title: "What Draws You Together", icon: "✨", duos: [
          { name: "Warmth meets steadiness", icon: "🌤️", roles: [{ warmth: 1, optimism: 0.6 }, { steadiness: 1, patience: 0.8 }], text: "{first} brings the sunshine and {second} brings the calm. Each of you feels safer around the other." },
          { name: "Curiosity meets focus", icon: "🔭", roles: [{ explore: 1, flex: 0.6 }, { persist: 1, analysis: 0.6 }], text: "{first} is always finding something new, and {second} is the one who makes it into something real. It's an exciting, useful kind of attraction." },
          { name: "Two of a kind", icon: "🪞", roles: [{ warmth: 0.6, humor: 0.6, flex: 0.6 }, { warmth: 0.6, humor: 0.6, flex: 0.6 }], text: "You recognise yourselves in each other: the same sense of humor, the same pace, the same quiet corners." },
          { name: "Bold meets gentle", icon: "🌹", roles: [{ boldness: 1, initiative: 0.8 }, { warmth: 1, patience: 0.8 }], text: "{first} goes first and {second} makes it feel okay. You each admire the thing you wouldn't do yourself." },
          { name: "Thinker meets feeler", icon: "💭", roles: [{ analysis: 1, structure: 0.5 }, { warmth: 1, social: 0.6 }], text: "{first} thinks it through and {second} feels it through. Together you get both halves of an answer." },
          { name: "Independent and loyal", icon: "🌲", roles: [{ autonomy: 1, flex: 0.5 }, { trust: 1, persist: 0.8 }], text: "{first} needs room and {second} gives it without worry. Trust makes the distance feel like closeness." },
        ] },
        { id: "balance", type: "duo", title: "How You Balance Each Other", icon: "⚖️", duos: [
          { name: "The Dreamer and the Builder", icon: "🏗️", roles: [{ invent: 1, optimism: 1, explore: 0.5 }, { structure: 1, persist: 1, steadiness: 0.5 }], text: "{first} imagines it and {second} makes it real. Together, the dream actually gets a front door." },
          { name: "The Spark and the Calm", icon: "🔥", roles: [{ boldness: 1, social: 0.5, initiative: 0.5 }, { steadiness: 1, patience: 1 }], text: "{first} brings the energy and {second} brings the steadiness. You each make the other more of what they're missing." },
          { name: "Two Soft Hearts", icon: "💞", roles: [{ warmth: 1, trust: 1 }, { warmth: 1, trust: 1 }], text: "You both lead with care. Home would be gentle, and the main thing to watch is saying the hard things too." },
          { name: "The Planner and the Free Spirit", icon: "🧳", roles: [{ structure: 1, analysis: 0.5 }, { flex: 1, explore: 0.5, boldness: 0.5 }], text: "{first} keeps the calendar and {second} keeps things from getting dull. Each of you needs the other more than you'd admit." },
          { name: "Partners in Curiosity", icon: "🔭", roles: [{ explore: 1, analysis: 0.5 }, { explore: 1, analysis: 0.5 }], text: "You'd rarely run out of things to talk about. Every book, trip and rabbit hole becomes a shared one." },
          { name: "The Talker and the Listener", icon: "🎧", roles: [{ social: 1, humor: 0.5 }, { patience: 1, warmth: 0.5, social: -0.5 }], text: "{first} fills the room and {second} makes sure everything that matters gets heard." },
          { name: "Two Independent Spirits", icon: "🌲", roles: [{ autonomy: 1, flex: 0.5 }, { autonomy: 1, flex: 0.5 }], text: "You each need room to be yourselves, and you respect that in each other. Closeness comes by choice, not by habit." },
          { name: "The Anchor and the Sail", icon: "⛵", roles: [{ steadiness: 1, persist: 0.5, warmth: 0.5 }, { explore: 1, optimism: 0.5, boldness: 0.5 }], text: "{first} keeps you grounded and {second} keeps you moving. It's the kind of balance that gets you somewhere." },
        ] },
        { id: "date", type: "pick", title: "Dream Date Style", icon: "🌹", options: [
          { name: "A slow evening at home", icon: "🕯️", needs: { social: -1, warmth: 0.8, patience: 0.5, structure: 0.3 }, text: "Good food, no plans and the best conversation of the week." },
          { name: "An adventure date", icon: "🧗", needs: { boldness: 1, explore: 1, flex: 0.7 }, text: "A hike, a new city or something slightly out of your comfort zone. You make each other braver." },
          { name: "A museum, then somewhere cosy", icon: "🏛️", needs: { explore: 1, analysis: 0.6, warmth: 0.6 }, text: "Wandering through something interesting and then talking about it for hours over something warm." },
          { name: "Cooking something ambitious together", icon: "🍝", needs: { invent: 1, humor: 0.6, warmth: 0.5, patience: 0.4 }, text: "Messy, funny and delicious. The best part is the part where it goes slightly wrong." },
          { name: "A lively night out", icon: "🎶", needs: { social: 1.2, humor: 0.8, optimism: 0.6 }, text: "Music, laughter and a crowd where you still only really notice each other." },
          { name: "A long walk and a longer talk", icon: "🌿", needs: { warmth: 1, steadiness: 0.6, analysis: 0.4, social: -0.3 }, text: "No destination, no rush and the kind of conversation that wanders somewhere real." },
          { name: "A movie marathon with snacks", icon: "🎬", needs: { humor: 0.6, flex: 0.6, warmth: 0.6, social: -0.3 }, text: "Comfort, commentary and strong opinions about the plot twist." },
          { name: "A spontaneous road trip", icon: "🚗", needs: { flex: 1, boldness: 0.8, explore: 0.8, structure: -0.8 }, text: "Pick a direction, turn the music up and decide where to eat when you're hungry." },
          { name: "A game night that gets competitive", icon: "🎲", needs: { compete: 1, humor: 0.8, social: 0.5 }, text: "Friendly teasing, sore losers and a rematch that's already scheduled." },
        ] },
        { id: "strengths", type: "list", source: "shared", title: "Relationship Strengths", icon: "🌟", intro: "What you naturally share:", empty: "You don't mirror each other. You complement each other, and that's its own kind of strength." },
        { id: "growth", type: "list", source: "conflicts", title: "Growth Areas", icon: "🌱", intro: "Places where understanding each other will help most:", empty: "No big gaps stand out. Keep checking in and you'll keep it that way." },
      ] },

    /* ------------------------------------------------------------ EVERYDAY */
    { id: "companionship", name: "Everyday", icon: "🧑‍🤝‍🧑", eyebrow: "EVERYDAY LIFE", tone: "neutral",
      blurb: "Siblings, parents, coworkers, classmates, roommates, mentors, business partners, even strangers: how do these personalities work side by side?",
      headlines: HL(
        "{A} and {B} work together very naturally. Most things will feel easy.",
        "{A} and {B} complement each other well, with differences that tend to help.",
        "{A} and {B} work well together, with a few differences worth understanding.",
        "{A} and {B} have different styles. With a little awareness, that can be a real advantage.",
        "{A} and {B} approach things differently, so clear communication will matter.",
        "{A} and {B} would need to work at understanding each other. The effort pays off."),
      sections: [
        { id: "teamwork", type: "category", category: "Teamwork", title: "Working Together", icon: "🤝", words: ["Takes effort", "Works well", "Natural fit"],
          high: "You tend to fall into a good rhythm quickly. Roles and expectations get sorted without much discussion.",
          mid: "You can work together well, especially when you agree up front who is doing what.",
          low: "You work in different ways. Setting clear roles from the start makes a big difference." },
        { id: "comm", type: "category", category: "Communication", title: "Communication", icon: "💬", words: ["Needs clarity", "Clear enough", "Easy"],
          high: "You tend to understand each other quickly, even when you're saying very little.",
          mid: "Most things get across fine. Checking that you meant the same thing helps with the rest.",
          low: "You each prefer a different style. Saying 'here's what I mean' out loud saves a lot of confusion." },
        { id: "decide", type: "category", category: "Decision Style", title: "Decision Making", icon: "🧭", words: ["Slow going", "Workable", "Aligned"],
          high: "You tend to weigh decisions in a similar way, so choices come quickly and nobody feels railroaded.",
          mid: "Decisions get made, though you might need to explain your reasoning to each other.",
          low: "One of you decides quickly and the other wants to think first. Agree on how long is reasonable." },
        { id: "calm", type: "who", title: "Who Stays Calmer Under Pressure?", icon: "🧘", weights: { steadiness: 1.5, patience: 1, flex: 0.5, structure: 0.5 },
          text: "{lead} tends to stay level when things get tense. {other} may bring the energy and the urgency.",
          tie: "You both stay about as calm as each other when things get stressful." },
        { id: "learning", type: "category", category: "Learning Style", title: "Learning Together", icon: "📚", words: ["Different paces", "Compatible", "Great study team"],
          high: "You'd learn well side by side. You like to approach new things in similar ways.",
          mid: "You can learn together if you pick a method that works for both of you.",
          low: "You each learn in your own way, so you'll teach each other as much as you learn." },
        { id: "project", type: "category", category: "Work Habits", title: "Project Compatibility", icon: "📋", words: ["Needs structure", "Solid", "Smooth"],
          high: "Your working habits fit. Deadlines, details and follow-through are unlikely to cause friction.",
          mid: "Your habits mostly match. Agree on deadlines and check-ins and projects should flow.",
          low: "You work at different speeds and in different ways. Shared milestones keep you in sync." },
        { id: "daily", type: "category", category: "Daily Lifestyle", title: "Daily Habits", icon: "🏡", words: ["Different rhythms", "Compatible", "Same rhythm"],
          high: "Your daily rhythms are similar, which makes sharing time, space or schedules easy.",
          mid: "Your routines overlap in most ways. A little give and take handles the rest.",
          low: "You keep different rhythms. A bit of planning avoids the little frictions." },
        { id: "respect", type: "category", category: "Leadership Balance", title: "Respect and Leadership", icon: "🏅", words: ["Needs clarity", "Mutual respect", "Easy balance"],
          high: "Neither of you needs to be in charge to feel respected, and neither minds taking the lead when it helps. It's an easy balance.",
          mid: "You respect each other's ways. Agree early on who decides what and it stays smooth.",
          low: "You might both want a say in the same things. Naming who leads on what saves a lot of friction." },
        { id: "boundaries", type: "category", category: "Social Energy Balance", title: "Boundaries and Space", icon: "🚪", words: ["Talk about it", "Well matched", "Naturally respectful"],
          high: "You tend to give each other the same amount of time and space without needing to say so. It's rare and restful.",
          mid: "You mostly agree on closeness and distance. A quick word when one of you needs more or less goes a long way.",
          low: "One of you may want more company than the other. Naming what you each need makes both of you feel respected." },
        { id: "reliable", type: "category", category: "Reliability", title: "Reliability", icon: "🧱", words: ["Needs reminders", "Dependable", "Rock reliable"],
          high: "If one of you says you'll do something, it gets done. You can lean on each other without checking.",
          mid: "You're mostly dependable, with the occasional slip. Light reminders keep things on track.",
          low: "You operate on different clocks. Agree on dates and what counts as 'done' and it gets much easier." },
        { id: "duo", type: "duo", title: "How You Work Together", icon: "🧩", duos: [
          { name: "The Planner and the Doer", icon: "📋", roles: [{ structure: 1, analysis: 0.5 }, { initiative: 1, persist: 0.5, flex: 0.5 }], text: "{first} maps out the steps and {second} gets them done. Projects tend to finish on time." },
          { name: "The Ideas Person and the Finisher", icon: "💡", roles: [{ invent: 1, explore: 0.5 }, { persist: 1, structure: 0.5 }], text: "{first} generates the ideas and {second} sees them through. You get both creativity and results." },
          { name: "The Talker and the Listener", icon: "🎧", roles: [{ social: 1, humor: 0.5 }, { patience: 1, warmth: 0.5 }], text: "{first} keeps the conversation going and {second} makes sure the important parts are heard." },
          { name: "Two Steady Hands", icon: "⚓", roles: [{ steadiness: 1, structure: 0.5 }, { steadiness: 1, structure: 0.5 }], text: "Dependable, organized and calm. Things get done the way they were agreed." },
          { name: "Two Idea Machines", icon: "⚡", roles: [{ invent: 1, explore: 1 }, { invent: 1, explore: 1 }], text: "Never short of ideas. The main task is deciding which ones to follow up on." },
          { name: "The Big Picture and the Details", icon: "🔍", roles: [{ explore: 1, initiative: 0.5, optimism: 0.5 }, { analysis: 1, structure: 1 }], text: "{first} sees where it's all going and {second} makes sure the details hold up." },
          { name: "The Calm and the Spark", icon: "🌤️", roles: [{ steadiness: 1, patience: 1 }, { initiative: 1, boldness: 0.5, social: 0.5 }], text: "{first} keeps things level while {second} keeps things moving. A good balance for busy days." },
          { name: "The Collaborators", icon: "🤲", roles: [{ warmth: 1, trust: 1 }, { warmth: 1, trust: 1 }], text: "You listen, share the work and give each other credit. Teamwork comes without much effort." },
        ] },
        { id: "strengths", type: "list", source: "shared", title: "Strengths", icon: "✨", intro: "What you share and can rely on:", empty: "Your strengths are different. Used well, that means more of the picture is covered." },
        { id: "blind", type: "list", source: "conflicts", title: "Blind Spots", icon: "👀", intro: "Where it helps to check in with each other:", empty: "No obvious blind spots. Keep communicating and you'll keep it that way." },
      ],
      relations: [
        { id: "siblings", icon: "👫", name: "Siblings", category: "Conflict Resolution",
          high: "As siblings you'd have the rare gift of arguing fairly. You can disagree on the television and still be the first to call each other.",
          mid: "As siblings you'd have the usual mix of teasing and loyalty. You tend to sort things out by the end of the day.",
          low: "As siblings you'd be quite different, which is its own kind of closeness. Giving each other the benefit of the doubt does a lot.",
          tip: "Keep a few traditions that are just yours." },
        { id: "cousins", icon: "🧒", name: "Cousins", category: "Fun Together",
          high: "As cousins you'd be the ones who disappear to invent a game at every family event.",
          mid: "As cousins you'd get along well at gatherings and find a few shared interests.",
          low: "As cousins you'd have different worlds, so family events are a good chance to compare notes.",
          tip: "Find the one thing you both secretly love." },
        { id: "parents", icon: "🏡", name: "Parent and child", category: "Communication",
          high: "As parent and child you'd speak the same language, which makes both the easy and the hard conversations a lot gentler.",
          mid: "As parent and child you'd understand each other well, with a few areas that need patience.",
          low: "As parent and child you'd see the world quite differently. Listening before advising makes a lasting difference.",
          tip: "Ask a question instead of giving a verdict." },
        { id: "coworkers", icon: "💼", name: "Coworkers", category: "Teamwork",
          high: "As coworkers you'd be the pair everyone hopes to be assigned with. Hand-offs are smooth and nobody is surprised.",
          mid: "As coworkers you'd collaborate well. Clear roles and a shared calendar keep it that way.",
          low: "As coworkers you'd work in different styles, so being explicit about expectations pays off.",
          tip: "Write down who owns what at the start." },
        { id: "classmates", icon: "🎒", name: "Classmates", category: "Study Partner",
          high: "As classmates you'd make an excellent study team, with enough chat to keep it fun.",
          mid: "As classmates you'd do well on shared work, once you've agreed on how to split it.",
          low: "As classmates you'd learn in different ways, so try each other's methods once before deciding.",
          tip: "Agree on a time limit and a break." },
        { id: "roommates", icon: "🏠", name: "Roommates", category: "Roommate",
          high: "As roommates you'd rarely argue about the dishes. Your rhythms and standards are similar enough to share space comfortably.",
          mid: "As roommates you'd get on well. A few house rules cover the rest.",
          low: "As roommates you'd have different ideas about home. A simple, written set of rules helps a lot.",
          tip: "Decide on quiet hours and the shared fridge on day one." },
        { id: "mentors", icon: "🧭", name: "Mentor and mentee", category: "Learning Style",
          high: "As mentor and mentee you'd click. The advice would land, and the questions would be the right ones.",
          mid: "As mentor and mentee you'd work well, with a bit of translation between how one teaches and the other learns.",
          low: "As mentor and mentee you'd learn in different ways, so ask how the other prefers to be taught.",
          tip: "Check in on what's actually useful." },
        { id: "business", icon: "📈", name: "Business partners", category: "Business Partner",
          high: "As business partners you'd move quickly in the same direction, trust each other's calls and complement each other well.",
          mid: "As business partners you'd make a solid team. Spell out roles, money and decisions in advance.",
          low: "As business partners you'd bring different instincts, which can be a strength if you agree how decisions get made.",
          tip: "Agree how you'll settle a disagreement before you have one." },
        { id: "strangers", icon: "👋", name: "Strangers", category: "Communication",
          high: "As strangers meeting for the first time you'd probably end up chatting longer than planned. Conversation would flow easily.",
          mid: "As strangers you'd get along comfortably and find common ground without much effort.",
          low: "As strangers you'd take a bit longer to find your rhythm, which is perfectly normal.",
          tip: "Start with something you're both curious about." },
      ],
    },
  ]);

  const S = (id, lens, title, icon, world, needs, lead, great, good, rough) => ({ id, lens, title, icon, world, needs, lead, great, good, rough });
  F.packs.add("scenarios", [
    /* ---- friendship */
    S("haunted-house", ["friendship"], "Escaping a haunted house", "🏚️", "", { steadiness: 1.3, boldness: 1, flex: 1, analysis: 0.6, humor: 0.4 }, { boldness: 1, initiative: 1 },
      "{lead} opens the creepy door and {other} spots the exit before anyone panics. You're out in twenty minutes with an excellent story.",
      "You get out eventually. There's some screaming, one wrong turn and a long argument about whose idea this was.",
      "{lead} says 'let's split up.' {other} says it's a terrible idea. You do it anyway. You'll both be telling this story for years."),
    S("road-trip", ["friendship"], "A cross-country road trip", "🚗", "", { flex: 1.2, humor: 0.8, patience: 1, explore: 0.8, structure: 0.3 }, { initiative: 1, explore: 1 },
      "The playlist is perfect, the detours are great and {lead} somehow finds the best diner in every state. You come home with an inside joke per state.",
      "You get there, with a few wrong turns, one rest stop dispute and a perfectly good picnic.",
      "Somewhere in the second week {lead} and {other} stop speaking about the route. The trip is saved by a roadside pie."),
    S("ikea", ["friendship"], "Building IKEA furniture", "🪑", "", { structure: 1.2, patience: 1.2, analysis: 0.8, steadiness: 0.6 }, { structure: 1, analysis: 1 },
      "{lead} reads the instructions, {other} sorts the screws, and the bookshelf stands straight on the first try. Suspiciously smooth.",
      "It takes a while and there's one disputed step, but the table is definitely a table by dinner.",
      "There are three screws left over and a wardrobe that is technically a wardrobe. {lead} blames the instructions and {other} blames {lead}."),
    S("dnd", ["friendship"], "Running a D&D campaign", "🎲", "", { invent: 1, humor: 0.8, social: 0.8, structure: 0.5, flex: 0.8 }, { invent: 1, initiative: 1 },
      "{lead} builds a world nobody wants to leave and {other} brings the best character voices. The one-shot is now a six-month campaign.",
      "The story wanders, the dice are cruel and the snacks are excellent. It's a great night regardless.",
      "{lead} spends three hours preparing an epic and {other} befriends the first villain. The plot is saved by a bad pun."),
    S("hogwarts", ["friendship"], "A Harry Potter adventure", "🪄", "Harry Potter", { explore: 1, warmth: 0.8, trust: 0.8, boldness: 0.7, analysis: 0.7 }, { analysis: 1, initiative: 1 },
      "{lead} finds the clue in the library and {other} is brave enough to follow it. Between you, the mystery doesn't stand a chance.",
      "You solve the mystery eventually, with a detention or two, and you both learn a surprising amount about the castle.",
      "You follow a hidden staircase that turns out to lead to the same corridor. {lead} insists it's a feature."),
    S("resident-evil", ["friendship"], "Surviving a Resident Evil outbreak", "🧟", "Resident Evil", { steadiness: 1.2, flex: 1, boldness: 0.8, structure: 0.6, trust: 0.6 }, { steadiness: 1, boldness: 1 },
      "{lead} keeps calm and {other} keeps moving. You find the key item, avoid the worst room and escape with ammunition to spare.",
      "You get out alive, a little bruised and with a very short list of things to never do again.",
      "Someone opens the one door they shouldn't. {lead} blames {other} and {other} blames the door. The door has no comment."),
    S("minecraft", ["friendship"], "Building a Minecraft world", "⛏️", "Minecraft", { invent: 1.2, persist: 1, explore: 0.6, structure: 0.5, humor: 0.4 }, { invent: 1, persist: 1 },
      "{lead} designs the castle and {other} finds the diamonds. By the end of the weekend you have a kingdom and a minor rail network.",
      "You build a surprisingly cozy base, and only one of you falls in lava twice.",
      "The house is half finished, there's a suspicious tunnel and {other} has accidentally released a creeper. Bold design choices."),
    S("marvel-mission", ["friendship"], "A Marvel-style mission", "🦸", "Marvel", { initiative: 1, boldness: 0.8, trust: 0.8, flex: 0.8, persist: 0.6 }, { initiative: 1, boldness: 1 },
      "{lead} takes point, {other} covers the angles, and the city is saved with time left for shawarma.",
      "You save the day, though the fight is messier than planned and the cleanup takes longer than the battle.",
      "The plan changes four times in the first five minutes. {lead} says it's fine. Collateral is, at least, creative."),
    S("dc-mission", ["friendship"], "A Justice League mission", "🦇", "DC", { persist: 1, warmth: 0.7, structure: 0.7, initiative: 0.8, steadiness: 0.7 }, { initiative: 1, persist: 1 },
      "{lead} sets the plan, {other} holds the line, and you finish with everyone safe and a very good speech ready.",
      "You get the job done, and a long debate about methods takes up most of the flight home.",
      "{lead} wants to talk it out and {other} wants to act. The villain is thrown by the argument and surrenders out of embarrassment."),
    S("star-wars", ["friendship"], "A Star Wars smuggling run", "🚀", "Star Wars", { flex: 1.2, boldness: 1, humor: 0.8, autonomy: 0.4, structure: -0.3 }, { boldness: 1, flex: 1 },
      "{lead} flies, {other} improvises, and you thread the asteroid field with a joke and about three seconds to spare.",
      "You make the delivery, minus one cargo crate and a lot of dignity.",
      "{lead} says 'never tell me the odds' and {other} immediately tells {lead} the odds. The odds are accurate."),
    /* ---- romance */
    S("hard-times", ["romance"], "Getting through a really hard stretch together", "🌧️", "", { steadiness: 1.3, trust: 1, warmth: 1, persist: 0.8 }, { steadiness: 1, warmth: 1 },
      "{lead} holds steady and {other} brings the warmth. By the time it passes you're closer than you were before.",
      "It's tough and you both have some low days, but you keep showing up for each other, which turns out to be enough.",
      "You each cope in different ways and for a while it feels like you're on separate islands. Talking about it is what brings you back."),
    S("future-plan", ["romance"], "Planning a future together", "🗺️", "", { structure: 1, initiative: 0.8, optimism: 0.8, trust: 0.8, analysis: 0.5 }, { structure: 1, initiative: 1 },
      "{lead} makes the spreadsheet and {other} makes it feel exciting. By the end of the evening you have a five-year plan and a very specific kitchen.",
      "You each bring a different vision and by the end you've blended them into one you both like.",
      "{lead} wants details and {other} wants to see how things unfold. You agree on one thing: it's a good conversation to keep having."),
    S("vacations", ["romance"], "Planning a vacation together", "🏝️", "", { flex: 1, explore: 0.8, patience: 0.8, humor: 0.6, structure: 0.3 }, { explore: 1, initiative: 1 },
      "{lead} finds the hidden gem and {other} makes it feel like home. You come back with a strong opinion about breakfast.",
      "You compromise between sightseeing and relaxing and find a mix that works for both of you.",
      "{lead} has an itinerary and {other} has a hammock. You each have a great time, a little separately, and agree to alternate next year."),
    S("pet", ["romance"], "Raising a pet together", "🐶", "", { patience: 1, warmth: 1, structure: 0.7, humor: 0.6, steadiness: 0.5 }, { structure: 1, patience: 1 },
      "{lead} sets the routine and {other} is the soft one the pet always runs to. It is, frankly, very cute.",
      "There are muddy paws, chewed shoes and some negotiation over whose turn it is. The pet is thriving.",
      "The pet gets two dinners because nobody remembers who fed it. It has become a very large and very happy pet."),
    S("build-home", ["romance"], "Building a home together", "🏡", "", { structure: 0.9, persist: 0.9, warmth: 0.9, trust: 0.8, invent: 0.5 }, { structure: 1, invent: 1 },
      "{lead} handles the plan and {other} makes it feel like yours. It's cozy, thoughtful and distinctly the two of you.",
      "It takes longer than planned, with a few debates about paint colors, but it ends up feeling like home.",
      "{lead} wants every detail decided and {other} wants it to evolve. For a while the sofa lives in the hallway. It's still your favorite."),
    S("goals", ["romance"], "Supporting each other's goals", "🌟", "", { warmth: 1, trust: 0.9, persist: 0.8, patience: 0.8, optimism: 0.6 }, { warmth: 1, persist: 1 },
      "{lead} is the first to cheer and {other} is the first to help. You each go further because the other is behind you.",
      "You each have your own dreams and sometimes your schedules clash, but you make room for each other's moments.",
      "You're both so focused on your goals that you forget to check in. A quiet dinner and an honest talk fixes it."),
    S("zombies-partners", ["romance"], "A zombie apocalypse, as partners", "🧟", "", { steadiness: 1.1, trust: 1, flex: 0.9, boldness: 0.7, persist: 0.7 }, { steadiness: 1, boldness: 1 },
      "{lead} handles the planning and {other} handles the improvising. You make a very good team, and you're oddly happy.",
      "You survive, with a few tense decisions and a long argument about whose turn it is to keep watch.",
      "You spend the first hour of the apocalypse debating the best route. The zombies, bored, wander off."),
    S("road-romance", ["romance"], "A road-trip romance", "🛣️", "", { flex: 1, humor: 0.9, warmth: 0.8, social: 0.5, explore: 0.7 }, { flex: 1, humor: 1 },
      "Wrong turns turn into the best parts. By the end of the trip you could write a movie about it, and you already know the soundtrack.",
      "The trip has its rough spots, but you share a lot of laughter and one particularly good motel.",
      "A flat tire, a wrong exit and a very bad playlist. You'll still agree it was one of your best weekends."),
    S("slow-burn", ["romance"], "A slow-burn love story", "🕰️", "", { patience: 1, trust: 1, warmth: 1, analysis: 0.4, steadiness: 0.5 }, { patience: 1, steadiness: 1 },
      "{lead} and {other} take their time, notice everything and say a lot with very little. When it finally arrives, it feels inevitable.",
      "It takes a while to find the right words, but the long pauses are comfortable and the end is worth waiting for.",
      "You both wait for the other to speak first. A very polite year passes. Someone finally breaks the silence, and it's lovely."),
    S("disaster-together", ["romance"], "Would you survive a disaster together?", "🌪️", "", { steadiness: 1.2, trust: 1, flex: 0.9, warmth: 0.7, persist: 0.7 }, { steadiness: 1, initiative: 1 },
      "{lead} makes the plan and {other} makes sure you both stay calm. You come out of it closer, and with a very good story about the night the power went out.",
      "It's a tough few days, with some stress and a few snapped words, but you take care of each other and get through it.",
      "You each react to stress differently, and for a while it feels like you're on separate rafts. Once you talk it through, you paddle in the same direction."),
    S("peaceful-home", ["romance"], "Would you build a peaceful home?", "🕊️", "", { warmth: 1, patience: 0.9, steadiness: 0.9, structure: 0.5, trust: 0.8 }, { patience: 1, warmth: 1 },
      "{lead} sets the tone and {other} keeps it warm. Your home would be the kind guests don't want to leave.",
      "It takes some negotiation about noise, tidiness and the thermostat, but you land somewhere calm that's yours.",
      "You each have strong ideas about what peaceful means. With a bit of compromise, you'd find a version of it that fits you both."),
    S("balance-test", ["romance"], "How would your personalities balance?", "⚖️", "", { warmth: 0.8, flex: 0.8, trust: 0.8, humor: 0.6, steadiness: 0.6 }, { warmth: 1, steadiness: 1 },
      "{lead} brings the grounding and {other} brings the spark. You make each other a little braver and a little calmer.",
      "You're quite different, and it mostly works. You teach each other to see another side of the same situation.",
      "You pull in different directions at first, and it takes some work to see that each of you is giving the other something missing."),
    /* ---- companionship (universally appropriate) */
    S("group-project", ["companionship"], "Finishing a group project", "📋", "", { structure: 1.2, persist: 1, analysis: 0.7, flex: 0.5 }, { structure: 1, initiative: 1 },
      "{lead} sets the plan and {other} keeps it moving. The project is finished a day early and nobody had to stay up all night.",
      "You get it done, with one last-minute scramble and a slightly longer meeting than expected.",
      "Everyone agrees on the plan and then does something different. The final result is surprisingly good, though no one can explain how."),
    S("family-event", ["companionship"], "Organizing a family gathering", "🏠", "", { structure: 1, warmth: 0.9, patience: 0.8, flex: 0.7, social: 0.5 }, { structure: 1, warmth: 1 },
      "{lead} handles the logistics and {other} makes sure everyone feels included. It's relaxed, organized and everyone goes home happy.",
      "A few things go sideways, like one forgotten dish and a late arrival, but you adapt and the day is lovely.",
      "The guest list changes twice and the menu once. It's chaotic, but somehow still a good party."),
    S("moving", ["companionship"], "Helping someone move house", "📦", "", { structure: 1, steadiness: 0.8, persist: 0.9, flex: 0.6, patience: 0.5 }, { structure: 1, persist: 1 },
      "{lead} labels the boxes and {other} carries the heavy ones. The truck is packed efficiently and the kettle is the first thing unpacked.",
      "It takes a bit longer than planned and one box is mysteriously missing, but everything arrives in one piece.",
      "Box labels are inconsistent, the sofa doesn't fit through the door and {lead} and {other} spend an hour on a diagram. It does eventually fit."),
    S("new-skill", ["companionship"], "Learning a new skill together", "🎓", "", { explore: 1, persist: 0.9, patience: 0.8, humor: 0.4, analysis: 0.5 }, { analysis: 1, explore: 1 },
      "{lead} reads the manual and {other} tries things out. Within a week you're better than the tutorial.",
      "You progress in bursts. Some days it's fast, some days you laugh at how bad you are, and you keep going.",
      "You each learn in a different way and you spend the first week arguing about the method. By week two you've borrowed each other's."),
    S("deadline", ["companionship"], "Hitting a tight deadline", "⏰", "", { steadiness: 1.2, persist: 1, structure: 0.8, initiative: 0.8, flex: 0.5 }, { steadiness: 1, initiative: 1 },
      "{lead} keeps everyone calm and {other} keeps everything moving. You deliver with a few minutes to spare and a good-natured sigh.",
      "It's tense for an hour, and then you find your rhythm and make it, just about.",
      "The deadline comes quicker than expected. {lead} and {other} deliver at the last second and agree to start earlier next time."),
    S("disagreement", ["companionship"], "Working through a disagreement", "🗣️", "", { patience: 1.1, warmth: 0.8, analysis: 0.7, steadiness: 0.8, trust: 0.5 }, { patience: 1, analysis: 1 },
      "{lead} listens and {other} explains. You each leave understanding the other's point and with a plan you both agree on.",
      "It takes a couple of attempts and a break, but you find a compromise you can both live with.",
      "You each make a very good point at the same time. It takes a snack break before anyone can hear the other."),
    S("small-stall", ["companionship"], "Running a stall at a local fair", "🏪", "", { social: 1, structure: 0.7, flex: 0.8, humor: 0.6, initiative: 0.6 }, { social: 1, initiative: 1 },
      "{lead} greets everyone who walks past and {other} runs the numbers. You sell out before lunch and take orders for next time.",
      "It's a busy day with a slow start and a very good afternoon, and you learn what you'd do differently.",
      "You set up in the wrong spot, the sign blows over and {lead} and {other} end up giving half the stock to the neighbors. Everybody leaves happy."),
    S("long-meeting", ["companionship"], "Surviving a long meeting that goes off track", "🗓️", "", { patience: 1, flex: 0.8, humor: 0.6, steadiness: 0.8, structure: 0.5 }, { structure: 1, patience: 1 },
      "{lead} steers it back to the agenda and {other} makes sure the quiet voices are heard. It ends on time with actual decisions.",
      "It runs over, but between you the main points get covered and the next steps are clear.",
      "The meeting about the meeting needs its own meeting. {lead} and {other} look at each other, nod and quietly reschedule everything."),
  ]);
})(typeof Forge !== "undefined" ? Forge : (globalThis.Forge = globalThis.Forge || {}));
if (typeof module !== "undefined" && module.exports) module.exports = Forge;
