/* =========================================================================
   ORGANIZATIONS (data only), part one: comics, wizards, outbreaks, the galaxy and Middle-earth. Registered as kind "orgs".
   An organization is a group with a culture, not a roster, so it is matched to a pair by its needs (like a world), not by members:
     needs          facet -> weight: the traits the organization rewards (negative = low is better)
     rewards        what it rewards, in words              struggles   who has a hard time there
     roles          four typical positions, by what each person brings: lead (takes charge), care (looks after people),
                    brain (plans and analyses), wild (improvises and takes risks)
     culture        how it feels inside                    leadership  how it is led
     communication  how people talk to each other          conflict    how disagreements are handled
   Original wording written for Forge; nothing here reproduces any franchise's text or symbols.
   ========================================================================= */
(function(F){
  "use strict";
  if (!F.packs) return;
  const O = (id, name, franchise, group, needs, blurb, rewards, struggles, roles, culture, leadership, communication, conflict) => ({ id, name, franchise, group, needs, blurb, rewards, struggles, roles: { lead: roles[0], care: roles[1], brain: roles[2], wild: roles[3] }, culture, leadership, communication, conflict });

  F.packs.add("orgs", [
    /* ---- Marvel ---- */
    O("shield", "S.H.I.E.L.D.", "Marvel", "Marvel", { structure: 0.9, analysis: 0.8, persist: 0.8, trust: 0.4, steadiness: 0.7, autonomy: -0.3 }, "A global intelligence-and-response agency that handles the strange so the public does not have to.", "Discipline, preparation and cool heads under pressure.", "Lone wolves, people who skip the briefing and anyone allergic to paperwork.",
      ["Director", "Medical officer", "Field analyst", "Special operative"], "Professional, secretive and mission-first, with plenty of dry humour in the corridors.", "A strict chain of command with a very capable, very private person at the top.", "Briefings, need-to-know and short, precise reports.", "Settled through procedure and quiet words, rarely in the open."),
    O("avengers-org", "The Avengers", "Marvel", "Marvel", { initiative: 0.8, boldness: 0.8, humor: 0.6, trust: 0.6, flex: 0.6, structure: -0.3 }, "A team of very different, very powerful people who show up when nothing else will work.", "Courage, improvisation and the willingness to put your ego aside, at least during the fight.", "People who cannot take a joke, share the spotlight or follow a plan they did not make.",
      ["Team captain", "Team heart", "Tech genius", "Wild card"], "Loud, loyal and full of in-jokes, with a good kitchen and a bad habit of arguing about strategy.", "A respected figure leads, and everyone else has strong opinions.", "Banter in the field, long arguments afterwards and a shared dinner.", "Heated, public and usually patched up over food."),
    O("x-men-org", "The X-Men", "Marvel", "Marvel", { warmth: 0.8, trust: 0.8, patience: 0.6, optimism: 0.6, persist: 0.7, autonomy: 0.2 }, "A school and a team for people who were told the world would never accept them.", "Compassion, resilience and a belief that people can change.", "Cynics, people who need a quiet life and anyone who cannot forgive.",
      ["Headmaster", "Counsellor", "Teacher-scientist", "Rogue instructor"], "Family-like, idealistic and a bit chaotic, with a dormitory feel and a strong moral centre.", "A visionary leads, supported by a council of strong personalities.", "Open and emotional, with long conversations at odd hours.", "Argued out in meetings and forgiven in the corridors."),
    O("x-force", "X-Force", "Marvel", "Marvel", { boldness: 0.9, autonomy: 0.8, flex: 0.7, persist: 0.7, trust: -0.2, optimism: -0.5 }, "A covert strike team that does the unpleasant things the others will not discuss.", "Pragmatism, nerve and the ability to live with hard choices.", "Idealists, rule-followers and anyone who needs to be thanked.",
      ["Strike leader", "Field medic", "Tactical planner", "Wet-work specialist"], "Grim, quiet and quietly loyal, with very dark humour and no speeches.", "A hard-nosed commander who owns the consequences.", "Short, coded and mostly over comms.", "Avoided until it cannot be, then settled bluntly."),
    O("fantastic-four-org", "The Fantastic Four", "Marvel", "Marvel", { explore: 0.9, invent: 0.8, warmth: 0.7, optimism: 0.7, humor: 0.5, trust: 0.7 }, "A family of explorers who are also a team, a laboratory and a very large breakfast table.", "Curiosity, loyalty and the ability to argue and hug in the same minute.", "People who prefer to work alone, avoid conflict or dislike surprises.",
      ["Mentor-scientist", "Family anchor", "Lab genius", "Hothead"], "Warm, noisy and curious, with the energy of a large family trip.", "A visionary scientist sets the agenda and a sensible partner keeps it grounded.", "Constant chatter, banter and shared meals.", "Shouted, then resolved over dinner."),
    O("guardians-org", "The Guardians of the Galaxy", "Marvel", "Marvel", { humor: 0.9, flex: 0.8, warmth: 0.7, boldness: 0.7, trust: 0.6, structure: -0.7 }, "A crew of misfits, thieves and rejects who became a found family by accident.", "Loyalty, humour and a willingness to improvise.", "Anyone who needs a schedule, a plan B or approval.",
      ["Captain", "Heart of the crew", "Engineer", "Chaos agent"], "Messy, funny and sincere, with a soundtrack and a lot of unresolved feelings.", "An unlikely leader whose main skill is getting the others to follow.", "Loud, personal and full of nicknames.", "Shouted, then forgotten."),
    O("midnight-sons", "The Midnight Sons", "Marvel", "Marvel", { steadiness: 0.8, autonomy: 0.7, boldness: 0.7, analysis: 0.5, optimism: -0.6, trust: 0.2 }, "A loose alliance of monster hunters and occult investigators who work the night shift.", "Steady nerves, dark humour and comfort with the unexplained.", "People who fear the dark, need daylight or want a normal routine.",
      ["Coordinator", "Spiritual advisor", "Occult scholar", "Monster hunter"], "Nocturnal, wry and quietly weary, with a deep mutual respect.", "Whoever is least likely to panic.", "Terse, practical and heavily coded.", "Handled with a drink and few words."),
    O("defenders-org", "The Defenders", "Marvel", "Marvel", { persist: 0.8, autonomy: 0.7, trust: 0.4, steadiness: 0.6, humor: 0.4, optimism: -0.3 }, "A reluctant alliance of street-level heroes who dislike teams and dislike letting each other down even more.", "Grit, independence and loyalty to a neighbourhood.", "People who need a hierarchy or a big public stage.",
      ["Reluctant leader", "Neighbourhood anchor", "Investigator", "Brawler"], "Gritty and local, with a lot of takeaway coffee and dry sarcasm.", "Nobody wants it, so the most responsible one gets it.", "Blunt and brief, often on rooftops.", "Rough in the moment, loyal afterwards."),
    O("sword", "S.W.O.R.D.", "Marvel", "Marvel", { analysis: 0.9, structure: 0.8, steadiness: 0.8, explore: 0.7, trust: 0.4, patience: 0.6 }, "The space-facing counterpart to the intelligence agencies, with its own problems and a much bigger sky.", "Rigour, calm and curiosity about the unknown.", "People who panic at scale or need frequent human contact.",
      ["Station commander", "Crew welfare", "Chief scientist", "Deep-space scout"], "Quiet, technical and slightly lonely, with an excellent coffee machine.", "A systematic commander who plans for everything.", "Logs, reports and measured language.", "Escalated by procedure, resolved over a long, patient review."),
    O("hydra", "Hydra", "Marvel", "Marvel", { structure: 0.9, compete: 0.8, initiative: 0.8, autonomy: -0.3, trust: -0.7, warmth: -0.6 }, "A secret order that believes order, properly applied, will cure the world, and that dissent is a defect.", "Ambition, discipline and obedience.", "Free thinkers, empaths and anyone who asks why.",
      ["Supreme leader", "Handler", "Scientist", "Enforcer"], "Cold, hierarchical and fearful, with a constant undertone of surveillance.", "Absolute, from the top, with no appeals.", "Orders go down; reports go up; nobody speaks sideways.", "Suppressed, with the problem removed."),
    O("aim", "A.I.M.", "Marvel", "Marvel", { analysis: 0.9, invent: 0.9, autonomy: 0.3, compete: 0.5, structure: 0.6, warmth: -0.4 }, "A corporate-style group of scientists in yellow suits whose answer to everything is more research.", "Cleverness, ambition and a willingness to push boundaries.", "Anyone cautious, ethical or content with the existing technology.",
      ["Scientist supreme", "Lab manager", "Chief researcher", "Experimental tester"], "Nerdy, status-obsessed and strangely cheerful, with long meetings and louder prototypes.", "The boldest scientist with the biggest budget.", "Technical, jargon-heavy and full of acronyms.", "Settled by who builds the better device."),
    O("hellfire-club", "The Hellfire Club", "Marvel", "Marvel", { social: 0.8, compete: 0.8, autonomy: 0.6, initiative: 0.7, flex: 0.6, trust: -0.6 }, "An exclusive club of the rich, powerful and ambitious, where every dinner is a negotiation.", "Charm, ambition and the ability to read a room.", "The earnest, the sentimental and the shy.",
      ["Inner Circle chair", "Social host", "Strategist", "Enforcer"], "Glamorous, competitive and quietly dangerous, with excellent wine.", "Whoever holds the most leverage that month.", "Courteous, coded and full of subtext.", "Waged through favours and well-timed embarrassment."),
    /* ---- DC ---- */
    O("justice-league-org", "The Justice League", "DC", "DC", { initiative: 0.8, persist: 0.8, warmth: 0.7, steadiness: 0.7, trust: 0.6, optimism: 0.5 }, "The world's most capable group of heroes, each of whom is also the best in a particular field.", "Courage, integrity and the ability to work with people more powerful than you.", "People who cannot compromise, need to be the best or dislike public attention.",
      ["Chairperson", "Moral centre", "Strategist", "Wild speedster"], "Principled, public and occasionally tense, with a great watchtower and some bad coffee.", "A respected figure convenes and the others respect that.", "Formal in public, relaxed in private.", "Debated openly, resolved through respect."),
    O("justice-society", "The Justice Society", "DC", "DC", { steadiness: 0.8, patience: 0.8, warmth: 0.7, structure: 0.6, trust: 0.7, optimism: 0.4 }, "The first generation of heroes, now mentors, with a long memory and a lot of stories.", "Experience, patience and a sense of tradition.", "People who dismiss the past or are impatient to move on.",
      ["Elder chair", "Mentor", "Historian", "Veteran scout"], "Warm, seasoned and slightly formal, with a trophy room and a family feeling.", "The longest-serving member, by courtesy.", "Stories, advice and the occasional lecture.", "Handled gently and with tact."),
    O("teen-titans-org", "The Teen Titans", "DC", "DC", { warmth: 0.8, humor: 0.8, social: 0.7, flex: 0.6, optimism: 0.6, trust: 0.7 }, "A group of young heroes who live in a tower and keep finding out who they are.", "Heart, humour and a willingness to grow.", "People who need a plan, a quiet room or a clear authority.",
      ["Team leader", "Empath", "Tech whiz", "Joker"], "Lively, loud and affectionate, with pizza and unresolved crushes.", "A rotating, informal lead who earns trust.", "Constant chatter and loud group chats.", "Shouted, then hugged."),
    O("titans", "The Titans", "DC", "DC", { persist: 0.8, trust: 0.8, warmth: 0.6, autonomy: 0.4, steadiness: 0.5, initiative: 0.5 }, "A grown-up team of former sidekicks who know each other too well and do not intend to stop.", "Loyalty, maturity and the ability to handle old grudges.", "Anyone who avoids history or seeks a clean slate.",
      ["Founder", "Heart", "Systems expert", "Rogue"], "Family-like, with history, rituals and an occasional grudge.", "The first among equals, by tradition.", "Candid and sometimes brutal.", "Settled by confronting the old issue and moving on."),
    O("young-justice", "Young Justice", "DC", "DC", { analysis: 0.7, flex: 0.7, trust: 0.7, structure: 0.5, humor: 0.5, autonomy: 0.4 }, "A covert team of young heroes with a secret mission and a mentor who did not tell them everything.", "Curiosity, discretion and the ability to follow a plan.", "People who cannot keep a secret or avoid conflict.",
      ["Field leader", "Team mediator", "Intel specialist", "Free spirit"], "Secretive, clever and a little tense, with a base and a lot of cover stories.", "A competent, slightly reluctant leader.", "Coded, careful and full of cross-talk.", "Settled in private, with an eye on the mission."),
    O("bat-family-org", "The Bat Family", "DC", "DC", { structure: 0.8, persist: 0.9, analysis: 0.8, trust: 0.6, warmth: 0.5, optimism: -0.2 }, "A scattered family bound by a mission, a city and an uncompromising sense of preparation.", "Discipline, preparation and quiet loyalty.", "People who improvise carelessly or avoid responsibility.",
      ["Patriarch", "Butler-steward", "Intelligence coordinator", "Acrobat scout"], "Dark, devoted and slightly sleep-deprived, with a lot of rooftop conversation.", "A founder with a plan for everything.", "Terse, coded and often silent.", "Brooded over, then dealt with through action."),
    O("suicide-squad-org", "The Suicide Squad", "DC", "DC", { flex: 0.8, boldness: 0.9, autonomy: 0.6, trust: -0.5, humor: 0.4, compete: 0.5 }, "A team of convicts offered a deal, a tight leash and a very bad mission.", "Pragmatism, nerve and the ability to follow orders you dislike.", "Idealists, perfectionists and anyone who needs to be trusted.",
      ["Handler", "Reluctant conscience", "Tactical planner", "Loose cannon"], "Edgy, sarcastic and distrustful, with a lot of bargaining.", "A hard-nosed administrator who holds the leash.", "Insults, threats and surprisingly honest asides.", "Settled by threat, bribe or a sudden act of loyalty."),
    O("birds-of-prey-org", "The Birds of Prey", "DC", "DC", { flex: 0.8, analysis: 0.7, autonomy: 0.6, boldness: 0.6, humor: 0.5, trust: 0.5 }, "A small, sharp team of women who run missions from a clock tower and a very good phone.", "Resourcefulness, independence and quick thinking.", "People who need constant direction or a big team.",
      ["Operations lead", "Safe-house keeper", "Information broker", "Field wild card"], "Witty, sharp and slightly chaotic, with great banter on the comms.", "The best coordinator, from a distance.", "Fast, clever and constant.", "Resolved with a joke and a favour."),
    O("green-lantern-corps-org", "The Green Lantern Corps", "DC", "DC", { steadiness: 0.9, structure: 0.8, persist: 0.8, boldness: 0.7, initiative: 0.7, compete: 0.3 }, "An interstellar police force powered by willpower, with sectors, rules and a lot of green light.", "Willpower, discipline and fearlessness.", "The easily frightened, the indecisive and the lazy.",
      ["Sector commander", "Peace officer", "Technical liaison", "Rookie ringbearer"], "Disciplined, proud and slightly bureaucratic, with a strong esprit de corps.", "A senior corps officer in a clear chain of command.", "Formal, with a rulebook for everything.", "Handled through the Guardians' formal review."),
    O("legion-of-doom-org", "The Legion of Doom", "DC", "DC", { compete: 0.9, initiative: 0.8, autonomy: 0.8, boldness: 0.7, trust: -0.8, warmth: -0.5 }, "A cabal of supervillains who share a headquarters and nothing else.", "Ambition, cunning and a very thick skin.", "The loyal, the humble and the collaborative.",
      ["Mastermind", "Dealmaker", "Schemer", "Brute"], "Egotistical, theatrical and tense, with a lot of capes and a lot of mutual suspicion.", "The most ruthless person in the room.", "Monologues, threats and veiled insults.", "Settled by betrayal, usually in public."),
    O("court-of-owls", "The Court of Owls", "DC", "DC", { structure: 0.9, patience: 0.8, autonomy: 0.4, compete: 0.6, trust: -0.7, steadiness: 0.7 }, "A centuries-old secret society that treats a city as an inheritance.", "Patience, discretion and loyalty to tradition.", "The impulsive, the open and the sentimental.",
      ["High court", "Keeper of rites", "Archivist", "Talon enforcer"], "Old, hushed and ritualistic, with an enormous sense of entitlement.", "A council of elders who rarely speak plainly.", "Ritual, formal and cryptic.", "Settled by a quiet vote and a very quiet departure."),
    O("checkmate", "Checkmate", "DC", "DC", { analysis: 0.9, structure: 0.8, initiative: 0.6, autonomy: 0.5, trust: -0.4, patience: 0.7 }, "A government intelligence agency that treats its heroes as pieces on a board.", "Strategy, discretion and a willingness to play the long game.", "People who cannot compartmentalise or who put friends before the plan.",
      ["White King", "Handler", "Analyst", "Black Queen operative"], "Cool, calculating and secretive, with a lot of long meetings.", "A strategist who never reveals the whole board.", "Compartmentalised, quiet and indirect.", "Resolved by reassignment."),
    /* ---- Harry Potter ---- */
    O("hogwarts-school", "Hogwarts", "Harry Potter", "Harry Potter", { explore: 0.9, humor: 0.5, warmth: 0.6, trust: 0.5, analysis: 0.6, flex: 0.5 }, "A school full of staircases, secrets and teachers with strong opinions about homework and dragons.", "Curiosity, courage and a willingness to ask questions.", "People who refuse to learn or to follow a sensible rule.",
      ["Headteacher", "House-parent", "Professor", "Mischief-maker"], "Quirky, old and cosy, with a strong sense of tradition and a talent for loopholes.", "A wise, slightly mysterious head sets a tone and lets the staff handle the rest.", "Letters, notices and a lot of corridor gossip.", "Debated by house, resolved by points."),
    O("gryffindor", "Gryffindor House", "Harry Potter", "Harry Potter", { boldness: 0.9, warmth: 0.6, trust: 0.6, initiative: 0.7, persist: 0.6, structure: -0.3 }, "A house that values bravery, even when it is slightly reckless.", "Courage, loyalty and a willingness to act.", "The cautious, the secretive and anyone who avoids a fight.",
      ["Captain", "Prefect", "Swot", "Daredevil"], "Loud, loyal and proud, with a lot of common-room debate.", "A natural leader who volunteers first.", "Direct and exuberant.", "Argued loudly, forgiven quickly."),
    O("ravenclaw", "Ravenclaw House", "Harry Potter", "Harry Potter", { analysis: 0.9, explore: 0.8, autonomy: 0.5, invent: 0.6, humor: 0.3, social: -0.2 }, "A house that treats curiosity as a virtue and a puzzle as a pastime.", "Intellect, creativity and independence of mind.", "The incurious, the dogmatic and the unimaginative.",
      ["Head of house", "Study-group host", "Scholar", "Eccentric inventor"], "Quiet, clever and individualistic, with a library and a riddle on the door.", "Whoever has the best idea.", "Questions, riddles and long explanations.", "Debated by argument, with citations."),
    O("hufflepuff", "Hufflepuff House", "Harry Potter", "Harry Potter", { warmth: 0.9, trust: 0.8, persist: 0.7, patience: 0.7, structure: 0.4, compete: -0.5 }, "A house that treats kindness, fairness and hard work as the point of being a wizard.", "Loyalty, fairness and consistency.", "People who must be the best, or who dislike teamwork.",
      ["Head of house", "Common-room host", "Quiet scholar", "Cheerful joker"], "Warm, patient and unpretentious, with excellent snacks.", "A kind, consistent presence.", "Open, warm and considerate.", "Resolved with a cup of tea."),
    O("slytherin", "Slytherin House", "Harry Potter", "Harry Potter", { compete: 0.9, initiative: 0.8, autonomy: 0.7, flex: 0.6, analysis: 0.6, trust: -0.3 }, "A house that values ambition, resourcefulness and the long game.", "Ambition, cunning and self-belief.", "The naive, the open and anyone allergic to politics.",
      ["Head of house", "Prefect", "Strategist", "Rule-bender"], "Polished, ambitious and a little guarded, with strong loyalties.", "The most capable, who knows how to wait.", "Careful, indirect and well-timed.", "Settled behind closed doors."),
    O("order-of-the-phoenix-org", "The Order of the Phoenix", "Harry Potter", "Harry Potter", { trust: 0.8, persist: 0.9, analysis: 0.6, steadiness: 0.7, boldness: 0.6, structure: 0.4 }, "A secret organisation of wizards committed to a quiet, dangerous war.", "Loyalty, discretion and perseverance.", "Gossips, glory-seekers and the easily panicked.",
      ["Leader", "Safe-house host", "Researcher", "Operative"], "Hushed, loyal and tired, with a kitchen table and a shared cause.", "A wise, guarded leader who gives each person a part.", "Coded, short and often by owl.", "Settled quietly in kitchens."),
    O("death-eaters", "The Death Eaters", "Harry Potter", "Harry Potter", { compete: 0.8, autonomy: -0.3, structure: 0.7, trust: -0.8, warmth: -0.7, initiative: 0.5 }, "A cult of followers organised around a shared prejudice and a feared leader.", "Obedience, ambition and cruelty.", "Anyone empathetic, independent or open-minded.",
      ["Leader's inner circle", "Recruiter", "Planner", "Enforcer"], "Fearful, status-driven and cruel, with a lot of one-upmanship.", "One feared figure at the top.", "Orders downward, flattery upward.", "Suppressed, with punishment."),
    O("ministry-of-magic", "The Ministry of Magic", "Harry Potter", "Harry Potter", { structure: 0.9, patience: 0.6, analysis: 0.5, steadiness: 0.6, trust: 0.2, flex: -0.4 }, "A vast, committee-ridden bureaucracy that regulates all magic and treats forms with great solemnity.", "Procedure, patience and an ability to survive a meeting.", "The impulsive, the creative and anyone who dislikes forms.",
      ["Minister", "Department head", "Policy analyst", "Auror"], "Formal, politicking and over-organised, with memos and tea trolleys.", "A politician with an eye on the next election.", "Memos, notices and hallway rumours.", "Delayed through committee."),
    /* ---- Resident Evil ---- */
    O("umbrella-corporation", "The Umbrella Corporation", "Resident Evil", "Resident Evil", { compete: 0.9, analysis: 0.8, structure: 0.7, autonomy: 0.3, trust: -0.8, warmth: -0.6 }, "A pharmaceutical giant with a very successful public face and a very unfortunate research programme.", "Ambition, secrecy and an appetite for risk.", "The ethical, the honest and the squeamish.",
      ["Executive director", "Research lead", "Lab analyst", "Security chief"], "Corporate, cold and secretive, with polished lobbies and very locked basements.", "A boardroom with a hidden agenda.", "Memos, compartmentalisation and need-to-know.", "Hidden, then denied."),
    O("bsaa", "The B.S.A.A.", "Resident Evil", "Resident Evil", { persist: 0.9, steadiness: 0.8, trust: 0.8, structure: 0.6, boldness: 0.7, warmth: 0.4 }, "A global anti-bioterrorism force of people who volunteer to go where the infection is.", "Courage, loyalty and calm under fire.", "The reckless, the timid and the self-promoting.",
      ["Commander", "Field medic", "Intelligence officer", "Point operative"], "Disciplined, comradely and tired, with a lot of shared meals before missions.", "A respected veteran leads from the front.", "Clear, brief and professional.", "Handled quickly in the field."),
    O("stars-unit", "S.T.A.R.S.", "Resident Evil", "Resident Evil", { flex: 0.8, trust: 0.8, steadiness: 0.7, boldness: 0.7, analysis: 0.5, humor: 0.4 }, "An elite police special-operations team that is better at its job than its public reputation.", "Skill, teamwork and quick thinking.", "The solitary, the slow and the unprepared.",
      ["Captain", "Medic", "Tactician", "Scout pilot"], "Close, professional and darkly funny, with a lot of cold coffee.", "A captain who inspires loyalty.", "Radio chatter and short, clear commands.", "Handled by the captain, with a joke."),
    O("blue-umbrella", "Blue Umbrella", "Resident Evil", "Resident Evil", { warmth: 0.7, trust: 0.7, steadiness: 0.7, persist: 0.7, structure: 0.5, optimism: 0.2 }, "A humanitarian response agency that cleans up other people's outbreaks and tries to keep the hope alive.", "Compassion, reliability and an ability to stay calm.", "The squeamish, the flippant and anyone who wants quick glory.",
      ["Field director", "Medical lead", "Containment scientist", "Rescue operative"], "Caring, hardworking and a little worn, with lots of field kits.", "A steady, compassionate organiser.", "Warm, practical and clear.", "Resolved by sitting everyone down to hear the whole story."),
    /* ---- Star Wars ---- */
    O("jedi-order-org", "The Jedi Order", "Star Wars", "Star Wars", { steadiness: 0.9, patience: 0.8, warmth: 0.5, analysis: 0.5, compete: -0.5, trust: 0.6 }, "An ancient order of peace-keepers trained to be calm, disciplined and detached from desire.", "Serenity, discipline and compassion.", "The impatient, the possessive and the easily angered.",
      ["Council master", "Healer", "Archivist", "Field knight"], "Calm, contemplative and slightly austere, with a lot of meditation.", "A council of elders and a master for each padawan.", "Calm, formal and sparing.", "Handled by meditation and quiet counsel."),
    O("sith-order", "The Sith Order", "Star Wars", "Star Wars", { compete: 0.9, initiative: 0.9, autonomy: 0.7, boldness: 0.8, trust: -0.9, warmth: -0.6 }, "An order of power-seekers who believe passion should be fed rather than disciplined.", "Ambition, intensity and cunning.", "The patient, the dependent and the forgiving.",
      ["Dark lord", "Whisperer", "Schemer", "Apprentice"], "Intense, rivalrous and paranoid, with a great deal of brooding.", "Whoever can defeat the last one.", "Manipulative and coded.", "Settled by duel."),
    O("rebel-alliance-org", "The Rebel Alliance", "Star Wars", "Star Wars", { optimism: 0.9, boldness: 0.8, trust: 0.7, flex: 0.7, humor: 0.5, persist: 0.7 }, "A scrappy coalition that believes the galaxy can be better, and has very little equipment.", "Hope, courage and improvisation.", "The cynical, the cautious and those who need guarantees.",
      ["Commander", "Medical officer", "Strategist", "Pilot"], "Scrappy, hopeful and slightly overworked, with a lot of shared sacrifice.", "A committee of committed leaders.", "Briefings and a lot of banter.", "Argued out in the hangar."),
    O("galactic-empire", "The Galactic Empire", "Star Wars", "Star Wars", { structure: 0.9, compete: 0.7, steadiness: 0.6, initiative: 0.5, trust: -0.6, warmth: -0.5 }, "A vast, orderly regime in which discipline is a virtue and dissent is a clerical error.", "Obedience, order and ambition.", "Free thinkers, empaths and the independent.",
      ["Admiral", "Medical officer", "Logistics analyst", "Trooper"], "Strict, hierarchical and anxious, with polished corridors and quiet fear.", "A rigid, top-down chain of command.", "Formal, controlled and sparing.", "Punished, quickly."),
    O("mandalorians", "The Mandalorians", "Star Wars", "Star Wars", { boldness: 0.9, structure: 0.6, persist: 0.8, autonomy: 0.5, trust: 0.5, warmth: 0.3 }, "A warrior culture with a code, a creed and a very good helmet.", "Honour, resilience and self-reliance.", "The cowardly, the dishonest and the unreliable.",
      ["Clan leader", "Armourer", "Tracker", "Bounty hunter"], "Proud, clannish and loyal, with a strong sense of identity.", "A clan leader who earns the title in combat.", "Short, direct and often ritual.", "Settled by challenge."),
    O("galactic-republic", "The Galactic Republic", "Star Wars", "Star Wars", { structure: 0.7, analysis: 0.6, patience: 0.7, social: 0.5, trust: 0.4, initiative: 0.3 }, "A sprawling democracy that depends on committees, negotiations and a very long agenda.", "Diplomacy, patience and procedure.", "The impulsive, the blunt and those who dislike debate.",
      ["Chancellor", "Senator", "Policy advisor", "Diplomatic envoy"], "Formal, political and slow, with elaborate etiquette.", "A council of representatives and a very careful chair.", "Speeches, motions and recesses.", "Debated indefinitely."),
    O("first-order", "The First Order", "Star Wars", "Star Wars", { structure: 0.8, compete: 0.8, initiative: 0.6, autonomy: -0.3, trust: -0.7, steadiness: 0.3 }, "A militarised movement built on the nostalgia of an empire and the ambition of its officers.", "Obedience, ambition and fervour.", "The independent, the sceptical and the compassionate.",
      ["Supreme leader", "General", "Strategist", "Stormtrooper"], "Rigid, theatrical and volatile, with a lot of rallies and a lot of anxiety.", "A distant, demanding figurehead.", "Orders and speeches.", "Handled by demotion.")
  ]);
})(Forge);
